### ISSUE TITLE
Random card (Rando Cardrissian)

### ISSUE THREAD

**Issue by bjohnson0604** [jakelauer/allbadcards#10]
Would love to see the option to add a random card to the pile. If the random is chosen everyone must be shameful and the last card czar repeats a turn.

**Comment by jakelauer** [comment]
This is planned! Rando Cardrissian will be added in the near future :)

**Comment by jakelauer** [comment]
This is complete!

**Comment by bjohnson0604** [comment]
Thank you. We love this!
