### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by arctic18cat** [jakelauer/allbadcards#101]
My idea is a scoreboad on the side with round number. shitty gifs on white screens

**Comment by jakelauer** [comment]
haha, shitty gifs?

**Comment by arctic18cat** [comment]
lol.. yeah gifs for waiting screen or something... Thanks for the game. We're doing a covid family game on discord. I have no coding exp but what can i help with other than money. I'll give ya some
    On Friday, April 24, 2020, 05:25:18 PM CDT, Jake Lauer <notifications@github.com> wrote:  
 
 


haha, shitty gifs?

**Comment by jakelauer** [comment]
Scoreboard is visible via the icon in the top right, I think that is sufficient for this one. Closing!
