### ISSUE TITLE
"Random" pile for allbad.cards

### ISSUE THREAD

**Issue by MrKazz** [jakelauer/allbadcards#105]
My idea is to allow a "random" pile to participate in the game as an additional player, but instead of randomly drawing cards from the deck, it plays the white card that has the most wins against the drawn black card (from all previous games played and recorded) that is not currently in one of the other human players' hands. 

This is great - thanks for making this and sharing it with us! :)

**Comment by jakelauer** [comment]
While I love this idea, it would require a fairly substantial amount of database storage and extra logic (essentially, every single round we would have to keep track of which card won and increment a counter in the database). Additionally, every random player would then have to play the first card that was 1) in their hand, 2) hadn't been played yet, 3) is in the deck chosen by the owner. Very difficult to do. I love the spirit of the idea though!
