### ISSUE TITLE
Cards 

### ISSUE THREAD

**Issue by taruslayer** [jakelauer/allbadcards#108]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced
Cards repeat too often
3. Did you see any errors?
No real error 
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type
C

**Comment by jakelauer** [comment]
Not enough detail
