### ISSUE TITLE
We dropped a player and couldn’t get them back.

### ISSUE THREAD

**Issue by Elliebee79** [jakelauer/allbadcards#109]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at? https%3A%2F%2Fallbad.cards%2Fgame%2Fchatty-dodo-74

2. Describe the problem you experienced
One of the players dropped out of the game suddenly but then couldn’t get back in.

3. Did you see any errors? No.

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser: Safari
- Device type: iPhone XR

**Comment by alexmill** [comment]
Happened to us (just now) too. Wonder if it's a server capacity issue?

**Comment by jakelauer** [comment]
Definitely could have been a server capacity issue at the time. When you say they couldn't get back in - could the player not rejoin as a new player? How could they not get back in? What was that person's experience - would the site not load? Did it say the game wasn't found?

**Comment by jakelauer** [comment]
I don't think this is an issue anymore
