### ISSUE TITLE
Game doesnt auto refresh

### ISSUE THREAD

**Issue by marstangg** [jakelauer/allbadcards#111]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
Should be fixed now!
