### ISSUE TITLE
Dynamic Cards

### ISSUE THREAD

**Issue by chesterjzara** [jakelauer/allbadcards#115]
My idea is...

A dynamic card that will use the judging player's name. For instance if "Tom" was judging, the card might say "Tom's Mom".

**Comment by jakelauer** [comment]
Renaming this just to the general idea of dynamic cards. 

This would be a difficult thing to create for a few reasons. The idea of dynamic cards is cool, but every card would have its own dynamic behavior. That is unless it's *always* a player's name... hmm. I'll think on it more.

**Comment by jakelauer** [comment]
Closing, although I will keep this in mind.
