### ISSUE TITLE
Option to leave game

### ISSUE THREAD

**Issue by hwhitwell** [jakelauer/allbadcards#12]
Hi,

It would be good to have an option to leave the game. At the moment, it seems that if someone if no longer able to play, the game stops because it is always waiting for their turn.

Love the online version though - GREAT job! :)

Hope you are well and safe!
Best wishes,
Harry

**Comment by jakelauer** [comment]
Thanks! It is possible to do this right now but the owner has to kick the person - they can't leave by themselves. However, I think that's a good idea for a feature.

**Comment by jakelauer** [comment]
Accidently closed.

**Comment by jakelauer** [comment]
This is possible now

**Comment by hwhitwell** [comment]
Wow - amazing! Thank you - great work!

Best wishes
Harry
