### ISSUE TITLE
Blank winner name after rage-removing winning player

### ISSUE THREAD

**Issue by OliB150** [jakelauer/allbadcards#123]
1. What URL was your game at?
https://allbad.cards/game/fast-fireant-6

2. Describe the problem you experienced
We played to 10 points and were robbed of our victory in a deciding round so in a fit of rage, removed the winning player from the roster. After which, the scoreboard displayed “Winner: !” as the winning players name was no longer available. 
The game had definitively finished however as no further rounds could be initiated. 

3. Did you see any errors?
No. 

4. Screenshots - If applicable, add screenshots to help explain your problem.
![E372CEC3-8683-4642-8857-CC7BD96277FC](https://user-images.githubusercontent.com/63923197/80321474-37cb9100-8815-11ea-93de-1ce8dbc6cee2.png)

5. Additional information
Please provide any additional helpful information, like:
- Browser: Safari for iPhone, unknown version
- Device type: iPhone 8 Plus, iOS 13.3.1
- Other: Game had been stable apart from this and provided a thoroughly enjoyable evening, especially in the current circumstances. Will be recommending.

**Comment by jakelauer** [comment]
This is hilarious.

**Comment by OliB150** [comment]
In the moment I didn’t think so, it was a clear demonstration of marital preference following a threat of sleeping on the sofa.
We definitely had the better answer!

Anyway, as mentioned this was the only problem we encountered with the gameplay so I just wanted to raise it!

**Comment by jakelauer** [comment]
I actually think this is an acceptable issue, hahaha. I kinda like it, even. Rage removing a winning player SHOULD have this kind of visceral, satisfying result.
