### ISSUE TITLE
Can't refresh cards on mobile browser

### ISSUE THREAD

**Issue by Kimberrley25** [jakelauer/allbadcards#127]
https://allbad.cards/game/dangerous-frog-78

When playing the game, some people on mobile devices were unable to "swap their cards" - those of us on laptops could see the "ok/cancel" prompt, but others could not. Unsure if this was on all mobiles though!

No errors were obvious, just could not see the prompt or couldn't confirm that we were okay with swapping our cards.

Device type was mobile, and mobile browsers - some native, some Chrome (Samsung mobile, iPhone, etc.)

**Comment by jakelauer** [comment]
Thank you for the detail! Others have reported this but without any information. Now I know what the problem is!

**Comment by jakelauer** [comment]
Fixed!
