### ISSUE TITLE
A card requires you to pick two answers but it isn't obvious

### ISSUE THREAD

**Issue by Kimberrley25** [jakelauer/allbadcards#128]
https://allbad.cards/game/dangerous-frog-78

The card "Here lies First Last, Year-2015, devoted friend, lover of _________." requires you to pick two answers, however doesn't let you know this.

Isn't a huge bug, but stumped us for a couple of mins. Might be handy to have "____ and ____." on the card so people know to choose two.

**Comment by jakelauer** [comment]
I think this is a bug, it looks like it should just require one card.

**Comment by jakelauer** [comment]
Fixed
