### ISSUE TITLE
UK edition card Pack - Happy to give you the list.

### ISSUE THREAD

**Issue by jasonBeattie** [jakelauer/allbadcards#13]
**Is your feature request related to a problem? Please describe.**
Not a problem. The UK edition would be great. 

**Describe the solution you'd like**
Option to choose the UK pack edition.
**Describe alternatives you've considered**

**Additional context**
Happy to supply you with the UK edition

**Comment by jakelauer** [comment]
Ooh, what format do you have it in?

**Comment by jasonBeattie** [comment]
What Format do you need? i can get it in multiple? i also have other Packs I could send

**Comment by jakelauer** [comment]
I'd take whatever you got. JSON is ideal. Here's the format for the existing packs: https://github.com/jakelauer/allbadcards/blob/master/server/data/all_cards.json

**Comment by jasonBeattie** [comment]
No worries. I will get it converted into JSON tomorrow, Once you have the packs. How long will it take to appear?

**Comment by jakelauer** [comment]
It mostly depends on when I have a chance to work on it and how similar the JSON is to what I have. I think at the most it'd be done this weekend.

**Comment by jakelauer** [comment]
@jasonBeattie Any luck with the JSON?

**Comment by jasonBeattie** [comment]
Hi. I have the CSV file. I have attempted the JSON file but cant seem to get the exact layout you have been using. If you have a CSV file you have used before to convert could you send it over so i can get the correct layout. 

https://drive.google.com/drive/folders/11Jny_dLHlCA0vxw3qG44vrXb-0ZgGcyu?usp=sharing

Apologies for the delay been a busy week! (Pregnant wife). 

I will also send you other packs once we have this one working :)

**Comment by jasonBeattie** [comment]
How are the files?

**Comment by jakelauer** [comment]
UK conversion pack and CardCast packs now supported!
