### ISSUE TITLE
Possible Localization in the future?

### ISSUE THREAD

**Issue by BaMuecke** [jakelauer/allbadcards#131]
I know its most likely no priority and there arent that many official localizations i know off, but for example germany has the "Cards vs. Humanity" fan localizations thats done quite well.

So i dont know if its possible to automate the card conversion (they show on their side the original card vs. the translated one) or if its possible at all, but i thought id ask and maybe someone has a good idea to incorporate both of them.

Best Regards and thanks for the great work!

**Comment by jakelauer** [comment]
Dupe of #86
