### ISSUE TITLE
A curse upon thee

### ISSUE THREAD

**Issue by razbakov** [jakelauer/allbadcards#138]
1. What URL was your game at?

https://allbad.cards/game/white-fish-62

2. Describe the problem you experienced

A curse upon thee! Many years from now, just when you think you're safe, _________ shall turn into _________.

This question had only one card to pick. 

3. Did you see any errors?

No

**Comment by jakelauer** [comment]
Fixed

**Comment by razbakov** [comment]
Wow! That was fast! Thank you very much!
