### ISSUE TITLE
[BUG] You are not the owner error

### ISSUE THREAD

**Issue by NoticeCorp** [jakelauer/allbadcards#14]
**Link to the game**
https://allbad.cards/

**Describe the bug**
When you cilck the player icon during set up, an error appears stating that "you are not the owner" even if you're the person who set up the game.

**To Reproduce**
start a new game, click on the player icon

**Expected behavior**
Not sure... that's why I clicked it

**Screenshots**
<img width="755" alt="Screen Shot 2020-04-16 at 9 12 24 am" src="https://user-images.githubusercontent.com/5598841/79398080-12dc5000-7fc3-11ea-9ee6-daf4fbc4fc8e.png">

**Desktop (please complete the following information):**
 - OS: Mac OS - latest release
 - Browser - Chrome - latest release

**Comment by NoticeCorp** [comment]
@jakelauer on another note, we may be interested in sponsoring your allbad.cards site - would like to see a sample tile since you don't have any yet... specifically wondering if there will be room to add any copy, or call to action outside the image.

**Comment by jakelauer** [comment]
The icon on the right removes a player from the game, so if you're the only player and remove yourself, then try to do an action that requires you to be the owner, you'll get this error. I'll have to add a tooltip to the icon to make it clearer :)

**Comment by jakelauer** [comment]
> @jakelauer on another note, we may be interested in sponsoring your allbad.cards site - would like to see a sample tile since you don't have any yet... specifically wondering if there will be room to add any copy, or call to action outside the image.

WRT this - I would like to stay away from anything that could be considered an "ad". I am happy to include a logo + company name. Potentially also a very short (several words) description. Maybe along the lines of "SquareSpace: Dream It; Make It". I'm happy to discuss further via email at `allbadcards(at)gmail.com`

**Comment by jakelauer** [comment]
Added a tooltip
