### ISSUE TITLE
520 Errors

### ISSUE THREAD

**Issue by CaptainFatt** [jakelauer/allbadcards#140]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at? All Bad Cards

2. Describe the problem you experienced
Getting 520 errors, and when we try to start a game, occasional JSON errors.

3. Did you see any errors?
Yes

4. Screenshots - If applicable, add screenshots to help explain your problem.
![Capture](https://user-images.githubusercontent.com/64622293/80774180-3f977800-8b2a-11ea-9ecf-ba9709b3dad5.PNG)

5. Additional information
Please provide any additional helpful information, like:
- Browser Chrome
- Device type Windows 10

**Comment by jakelauer** [comment]
Fixed! Apologies for the interruption.
