### ISSUE TITLE
Add support for multiple Cardcast decks at once

### ISSUE THREAD

**Issue by archer007** [jakelauer/allbadcards#143]
My idea is...
When adding Cardcast decks, accept a space or comma separated list of cardcast deck codes instead of just a single code

**Comment by jakelauer** [comment]
What is the use case for this? It sounds way easier to copy one pack at a time instead of making a comma-separated list

**Comment by archer007** [comment]
So that if you have a favored set of packs you can copy-paste the whole list in

**Comment by jakelauer** [comment]
This is done! You can copy in a comma-separated list now.
