### ISSUE TITLE
Card typo

### ISSUE THREAD

**Issue by MyrrhDev** [jakelauer/allbadcards#145]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/blue-dragon-9
2. Describe the problem you experienced
Just a card typo: "You might develop an 'intrest..'
3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.
![Screenshot from 2020-05-01 10-52-39](https://user-images.githubusercontent.com/24651756/80794370-10205400-8b9a-11ea-842d-1a12b5fc33f9.png)

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
Fixed!
