### ISSUE TITLE
Game Restart Broken

### ISSUE THREAD

**Issue by sporkified** [jakelauer/allbadcards#146]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/stupid-snail-46

2. Describe the problem you experienced
When trying to restart the game at the end, it threw an error and wouldn't allow me to.

3. Did you see any errors?
Cannot read property 'guid' of undefined

4. Screenshots - If applicable, add screenshots to help explain your problem.
![Screenshot (2)](https://user-images.githubusercontent.com/64655718/80824871-2ef10b80-8bd7-11ea-92c3-c776fef9498d.png)

5. Additional information
Using the latest version of Chrome and a tiny cheap laptop. The rest of the game seemed to work fine, it was just annoying having to re-invite everyone and re-add custom packs. The first game we had didn't use any custom packs but still had this issue so it's not to do with them. Thanks for checking this out :)

**Comment by jakelauer** [comment]
Fixed!
