### ISSUE TITLE
It froze at choosing winner

### ISSUE THREAD

**Issue by Grabru** [jakelauer/allbadcards#148]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
Need more details here. What do you mean by froze? What was the URL?
