### ISSUE TITLE
Link Doesn't Work 

### ISSUE THREAD

**Issue by tamsinels** [jakelauer/allbadcards#151]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/curvy-stingray-98

2. Describe the problem you experienced
Stopped working - everyone else continued in the game 

3. Did you see any errors?
No 

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser - chrome 
- Device type - laptop windows

**Comment by jakelauer** [comment]
I think this is fixed now
