### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by sammyhaa** [jakelauer/allbadcards#152]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/kind-cheetah-57
2. Describe the problem you experienced
It stopped me playing the game and just told me something broke. Refresh 
3. Did you see any errors?
Something broke. Refresh
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type
Google pixel 3xl on chrome

**Comment by jakelauer** [comment]
I think this is fixed now
