### ISSUE TITLE
Possible to submit any card as an answer

### ISSUE THREAD

**Issue by BenChand** [jakelauer/allbadcards#154]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/api/game/play-cards

2. Describe the problem you experienced
Repeatedly played the card: {"packId":"second_expansion","cardIndex":62} (Spring Break!) over multiple rounds.

3. Did you see any errors?
No errors, it let me do it!

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

Browser shouldn't matter, I used curl.

----------------

I have no idea how to compile typescript but the fix should be possible in the playCard function:
https://github.com/jakelauer/allbadcards/blob/master/server/Games/GameManager.ts#L565

Before creating the newGame constant, iterate over cardIds and ensure that each one is present in existingGame.players[playerGuid].whiteCards. If a submitted card isn't present in the whiteCards array, throw an exception

**Comment by jakelauer** [comment]
This one is more worrisome. Will fix.

**Comment by jakelauer** [comment]
Fixed!
