### ISSUE TITLE
Possible to submit incorrect number of cards

### ISSUE THREAD

**Issue by BenChand** [jakelauer/allbadcards#155]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

2. Describe the problem you experienced

The playCard function doesn't validate the number of cards submitted, allowing you to submit more or less than the pick size defined for the black card. This can lead to strange issues in the UI!

Get black card definition from card manager and check pick size with cardIds length. I have no idea if this compiles:

```
	public async playCard(gameId: string, player: IPlayer, cardIds: CardId[])
	{
		const playerGuid = player.guid;

		const existingGame = await this.getGame(gameId);
		const playerData = existingGame.players[playerGuid];
		const isRandom = playerData.isRandom;
		if(!isRandom)
		{
			this.validateUser(player);
		}

		const blackCardDef = await CardManager.getBlackCard(existingGame.blackCard);
		if (cardIds.length !== blackCardDef.pick) {
			throw new Error("Incorrect number of cards submitted!");
		}

		const newGame = {...existingGame};
		newGame.roundCards[playerGuid] = cardIds;
		newGame.playerOrder = ArrayUtils.shuffle(Object.keys(newGame.players));

		await this.updateGame(newGame);

		return newGame;
	}
```

**Comment by jakelauer** [comment]
The UI prevents this from happening, so it's not a horrific problem. Noted, though.

**Comment by jakelauer** [comment]
Fixed!
