### ISSUE TITLE
[BUG] "My Cards Suck" doesn't reactivate after 5 rounds

### ISSUE THREAD

**Issue by treznor** [jakelauer/allbadcards#16]
**Link to the game**
https://allbad.cards/game/UV5pV6gi4

**Describe the bug**
The 'My Cards Sucks' button stayed grayed out multiple games even though it says it should only stay grayed for 5 rounds.

**To Reproduce**
1. Click My Cards Suck
2. Wait 5 rounds
3. Note that it doesn't become usable again

**Expected behavior**
My Cards Suck button becomes usable after 5 rounds

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jakelauer** [comment]
Anything for you, Trent Reznor!

**Comment by treznor** [comment]
Thanks :)

By the way, maybe 5-10 minutes after I submitted this bug the button
started working again... Hope this isn't too hard to track down :)

**Comment by jakelauer** [comment]
I'll keep my eye on it.

**Comment by NoobieMatt** [comment]
Hey Jake, super work thank you, Just played a game and noticed same bug, 4 players all not seing "my cards" suck reactivated after several rounds (played 3 games of 8 rounds - played "May cards suck on first game at about 6th round)

**Comment by jakelauer** [comment]
I believe this happens when you restart a game. If you use My Cards Suck in round 22 of a game, then restart the game, the code thinks you have to wait until round 27 to use it again. I have added code to reset the count if you restart a game.

**Comment by treznor** [comment]
Thanks for the update!

**Comment by NoobieMatt** [comment]
Thanks Jake, again superb stuff, friends and I not laughed so much since this lockdown started. Will drop you a couple of £ on the buy me coffee link 👍👍👍
