### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by jcarrera94** [jakelauer/allbadcards#165]
My idea is...
maybe keep the scoreboard visible at all times?

**Comment by dennmuel** [comment]
Would this be fixed by #162?

**Comment by jakelauer** [comment]
I believe it would - but I wouldn't say #162 is something I'm guaranteed to do. That's just there for tracking purposes. My thoughts on this are that adding the scoreboard as visible all the time is a significant amount of screen/scroll space to use on mobile. I'm not sure what is gained by doing so, when you can easily access the scoreboard from the top menu.

**Comment by dennmuel** [comment]
I agree. Personally, I like the menu solution since it gives me the freedom to choose, if I want to pay attention to the scores or not. Still it sounds like a duplicate issue to me.

**Comment by jakelauer** [comment]
Closing, don't think this is necessary
