### ISSUE TITLE
Repeat cards

### ISSUE THREAD

**Issue by nealhead** [jakelauer/allbadcards#166]
Players can currently have the same card

**Comment by jakelauer** [comment]
Which card did you see twice?

**Comment by nealhead** [comment]
Two players got the "my cousin" card. Also, this is hilarious to be submitting this.

**Comment by dennmuel** [comment]
Looks like there are two packs, that contain a "My hot cousin" card: seasons_greetings_pack.json and 2012_holiday_pack.json (and several others differently wording the same concept).

I can't really estimate if string comparison for exact duplicates over all used cards would be impacting performance too much...

**Comment by jakelauer** [comment]
I wonder if I should just ditch one of those packs. They already had other dupes... probably worth just removing the 2012 pack.

**Comment by dennmuel** [comment]
Sounds sensible. If people really need it, they can still activate it manually.
