### ISSUE TITLE
All Bads Card, multiselect problem.

### ISSUE THREAD

**Issue by elcman** [jakelauer/allbadcards#168]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/

2. Describe the problem you experienced
"You know, once you get past _________, _________ ain't so bad." card didn't allow us to pick two cards.

3. Did you see any errors?
No. We just picked singles and moved on.

4. Screenshots - If applicable, add screenshots to help explain your problem.
... missed it.

5. Additional information
Please provide any additional helpful information, like:
- Browser: Chrome
- Device type: Windows 10

**Comment by BadgerCode** [comment]
I've found the card you mentioned and fixed it in #169
