### ISSUE TITLE
More pictures of badgers 

### ISSUE THREAD

**Issue by GartRuzza** [jakelauer/allbadcards#17]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 

I am always frustrated then i go to your page and I don’t see pictures of badgers 

**Describe the solution you'd like**

I want to see more pictures of badgers 

**Describe alternatives you've considered**

Maybe weasels? Idk man 

**Additional context**

I don’t have screenshots but you get the idea

**Comment by jakelauer** [comment]
🦡🦡🦡🦡
