### ISSUE TITLE
Display card pack on cards

### ISSUE THREAD

**Issue by korzynski** [jakelauer/allbadcards#172]
Add the name of the card pack on each card, so that players can determine the source of particularly good or bad cards. We got a bunch of weird British/Australian cards that made no sense but no one really knows where they came from.

**Comment by dennmuel** [comment]
I'd suggest to not show the source directly, but instead have a subtle "info" icon like "(i)" or "..." to open the info. Then there could even be a small menu, if there are other things one would like to do with the card, e.g. blocking them for subsequent games of the same session.

**Comment by jakelauer** [comment]
Yes, gonna use #75 as the canonical issue here
