### ISSUE TITLE
After a few games the default main packs are added back to the game after removed at start.

### ISSUE THREAD

**Issue by SoulEvans07** [jakelauer/allbadcards#173]
1. What URL was your game at?
young-dragonfly-51

2. Describe the problem you experienced
I removed all main decks from the game and added a few deck from CardCast (SCTTM, Z5YTT, Z5FGV) because my family don't speak english. After a few games we noticed that english cards poped up in the game. I assume these are the main decks which are preselected at the room creation but I removed all of them at start. The time when the english cards were added was random but I think it was after the game had a small connectivity issue and reloaded the room.

3. Did you see any errors?
No, just a warning about the socket reconnection in the console.

~4. Screenshots - If applicable, add screenshots to help explain your problem.~

5. Additional information
- Browser: Chrome, Version 81.0.4044.122 (Official Build) (64-bit)
- User-Agent: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
- OS: Windows 10 64-bit

**Comment by jakelauer** [comment]
Interesting. To be clear, did this happen after restarting a game after it finishes? Or is this after a few rounds in one game.

**Comment by SoulEvans07** [comment]
After a few rounds into the game. But there was one game where we could finish it (won 7 games) and after I clicked the restart game the main cards were added too.

**Comment by jakelauer** [comment]
I found the culprit for this and it should be fixed this week

**Comment by jakelauer** [comment]
This should be resolved
