### ISSUE TITLE
Check to leave game

### ISSUE THREAD

**Issue by lrmull** [jakelauer/allbadcards#176]
My idea is...  checking “are you sure?” before allowing players to leave the game.  I pressed the button by mistake to try to edit my name and suddenly lost all my points and my place in the game. :/

**Comment by jakelauer** [comment]
Agree that this is a good idea

**Comment by haydius** [comment]
In addition to an in-game alert, would be well worth implementing a browser window-level check too.

Chrome no longer supports custom messages but this will trigger the "unsaved changes" prompt when closing the tab (i.e. have it active if a game is up) which will allow you to prevent accidental closure of the tab/browser when a game is on whereas an in-game confirmation would not prevent closing the tab or browser while on another tab or program

```javascript
window.addEventListener("beforeunload", function (e) {
    var exitAlert = 'Baby please don\'t go...';
 (e || window.event).returnValue = exitAlert; //IE Support
    return exitAlert; // All other browsers (Gecko+Webkit)
});
```
