### ISSUE TITLE
Mis-matched cards for players

### ISSUE THREAD

**Issue by DeuceDawg22** [jakelauer/allbadcards#178]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
There's no detail here.

**Comment by DeuceDawg22** [comment]
Updated, apologies. Didn’t take my responses the first time.
