### ISSUE TITLE
Blank Cards

### ISSUE THREAD

**Issue by bulldogs3401** [jakelauer/allbadcards#179]
My idea is...
just empty cards that you can fill in to make things more interesting

**Comment by dennmuel** [comment]
Would this be the same as #102, #119 and #120?

**Comment by bulldogs3401** [comment]
Yep, sorry about that. I was just putting it out there, thought it might
have been suggested, but never looked into it.

**Comment by dennmuel** [comment]
All good, still a cool idea! :) I don't have anything to say in this project, I'm just trying to help by finding duplicates, fixing typos and that kinda stuff.

**Comment by jakelauer** [comment]
Yes, dupe of #102 :) Thanks @dennmuel !
