### ISSUE TITLE
Game does not notify you that you left/were kicked

### ISSUE THREAD

**Issue by hjoies** [jakelauer/allbadcards#180]
https://allbad.cards/game/ancient-wasp-61

every time I tried to play a card, I would get a message saying "isRandom" is undefined. this happened with every card.

I was using google chrome in a Chromebook.

**Comment by jakelauer** [comment]
I experienced this as well, were you playing a public game at the time?

**Comment by hjoies** [comment]
yes. here is a screenshot of what happened 
![Screenshot 2020-05-03 at 00 47 02](https://user-images.githubusercontent.com/64725371/80908801-c9387880-8cd7-11ea-9903-f81281c7519f.png)

**Comment by jakelauer** [comment]
Yes, this is a bug. It happens when you get removed from the game by the owner. Your game doesn't refresh after that, and since you're not technically in the game, it fails to play a card.

**Comment by hjoies** [comment]
Ok thank you, I was hoping it was something like that because I was using at as a trial to see if it worked on my computer so that I could host a game with my friends

Your student,
Hailey Stefan
She/Her
480884

**Comment by jakelauer** [comment]
I need to sort this out. The main issue is that leaving a game removes you from the list of WebSocket connections, so I can't send a notification to you anymore. I need to change it so it sends you a notification BEFORE removing you

**Comment by haydius** [comment]
And in the case where the booted person was offline or experiencing network issues during the notice (potentially why they were booted) it may be worth having a "heartbeat" kind of check client side to check if connection is up and session is still valid so that in the case the client did not receive the kicked command it can figure it out itself
