### ISSUE TITLE
Custom cards (local to the game)

### ISSUE THREAD

**Issue by STcraft** [jakelauer/allbadcards#183]
My idea is...

A way to enter a list of custom cards (like a multi-line textbox to put in your own content without card-cast)

As for the black cards you can put in a _ (underscore) character to denote a slot (0 = pick 1 (default), 1 = pick 1, 2 = pick 2, etc..)  On display it will add some more underscores for better readability.

Thought it would be a nice addition, that way the host can put in their own in-jokes for example.

**Comment by jakelauer** [comment]
While I agree that this would be cool, at this point, the amount of work investment it would take is unfeasible. Just for context, it would require:
- An input method that corrected mistakes (such as using many underscores for a blank)
- A way to add/delete cards
- A way to save cards (who wants to do all that work every game?)
- A method by which to include a card pack in a game form a database
- A way to find the pack you made
....etc

That's a TON of stuff! That's the really nice thing about using CardCast. They built all of that stuff already and it's easy to use. Fortunately, you can just hop on there and make your own list of custom cards :)
