### ISSUE TITLE
UI/UX: Visually distinguish black card buttons

### ISSUE THREAD

**Issue by dennmuel** [jakelauer/allbadcards#187]
I've seen some people accidentally skipping a black card instead of playing it. If find the time, I'll try to make a PR that visually distinguishes the two buttons.

**Comment by jakelauer** [comment]
Agree with this

**Comment by haydius** [comment]
Idea: Have a less bold style for the skip button and/or have its opacity reduced unless pressed/hovered on.

**Example:**
![image](https://user-images.githubusercontent.com/4658897/81032196-ff961380-8ee2-11ea-9a52-f89038a71f12.png)

**Comment by dennmuel** [comment]
Very nice @haydius , that's more or less what I had in mind. :)
Alternatively, "Skip Card" could be rendered as a small text and not look like a button at all (like e.g. a link). But I think we'll go with something in the direction of your suggestion.

**Comment by jakelauer** [comment]
Done!

**Comment by dennmuel** [comment]
Thanks! (Sorry for bring too slow, been busy writing a custom deck xD)
