### ISSUE TITLE
Refreshing the page/going to dark mode resets settings

### ISSUE THREAD

**Issue by CyberDefenseTiger** [jakelauer/allbadcards#188]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/neat-fly-14

2. Describe the problem you experienced:
When going to dark mode or refreshing the page for any reason when creating the game it resets the main card packs you selected. All other settings remain but the main card packs settings reset

3. Did you see any errors? No

4. Screenshots - If applicable, add screenshots to help explain your problem.  I can get them but it does not seem worth it.

5. Additional information
Please provide any additional helpful information, like:
- Browser  Google Chrome
Version 81.0.4044.129 (Official Build) (64-bit)
- Device type Windows 10 laptop

**Comment by jakelauer** [comment]
This will be fixed by another issue (#173) - settings as a whole should not be resetting because they are automatically saved to the database, but the card packs have a bug that sets them to defaults even if you have changed them. Keep an eye on that bug for a fix! It should be within the next couple days

**Comment by CyberDefenseTiger** [comment]
Thank you and I'm sorry I did look for anything similar and didn't see that
one. I'm glad you are so on top of it though. It's a great site. I'm not a
programmer by any means but if you need help with something please let me
know.

**Comment by jakelauer** [comment]
Don't worry! Your issue and the other issue have different symptoms so without knowing why, they seem like totally different problems. I do this for a living and even people whose job it is to file bugs make duplicates all the time. It's part of the job!

Thanks for the offer :) If you have a specialty that would be applicable, let me know!
