### ISSUE TITLE
Entering invalid / mistyped Custom Card Packs

### ISSUE THREAD

**Issue by haydius** [jakelauer/allbadcards#191]
If an invalid code is entered (still 5 alphanumerics, but not a valid card pack code), the remote resource 404s (expected) but an empty MuiListItem is added to the card list element anyway.
![image](https://user-images.githubusercontent.com/4658897/81031332-04a59380-8ee0-11ea-86f9-b3a2ddca93c5.png)
Card pack code is also saved to game's data.

Possible fix:
_Only accept a HTTP response status of 200 (valid, content recieved in full) and reject all others as failure (do not add to list or game metadata) with toast/alert to user that a valid card pack was not found_

**Comment by jakelauer** [comment]
No longer relevant, now that we have our own custom packs

**Comment by jakelauer** [comment]
PS RIP CardCast
