### ISSUE TITLE
URL redirect for dead end page

### ISSUE THREAD

**Issue by haydius** [jakelauer/allbadcards#192]
Not really a bug, more something I noticed while browsing / URL testing.

I can see already that if providing an invalid game name/url it will eventually revert back to the current active game. Handy!

If navigating to just **allbad.cards/game** it  sits on an empty page with no game active.

Could have this redirect this to an active game (if their one is found such as above) or bounce them to the home screen

**Comment by jakelauer** [comment]
Done!
