### ISSUE TITLE
Cannot convert null object when pressing next round

### ISSUE THREAD

**Issue by BEMZ01** [jakelauer/allbadcards#194]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/hungry-gecko-62
2. Describe the problem you experienced
Went to press on Next it errored
3. Did you see any errors?
can not convert null object
4. Screenshots - If applicable, add screenshots to help explain your problem.
 N/A
5. Additional information
Please provide any additional helpful information, like:
- Browser Firefox
- Device type Windows 10 64 bit

**Comment by sugaroverflow** [comment]
we just experienced this issue at https://not.allbad.cards/game/strong-bee-4328

I believe it might be from removing a player earlier

**Comment by jakelauer** [comment]
Closing as there have been no reports for 2 weeks
