### ISSUE TITLE
See all cards and remove some of them

### ISSUE THREAD

**Issue by configurator** [jakelauer/allbadcards#195]
When I create a game, I sometimes want most of a pack except a few cards which would be "going too far" for the group that's playing. I'd like the ability to

- see all the cards in the packs I've selected
- remove some of those cards, leaving the rest intact

**Comment by jakelauer** [comment]
I see why this would be useful, but it's so much work for someone to do when creating a game, and it's a ton of work to support. Just untenable really :(
