### ISSUE TITLE
Card needs 2 responses

### ISSUE THREAD

**Issue by JonnyOThan** [jakelauer/allbadcards#198]
This card requires two responses, which doesn’t make sense.

![655E5C53-2F3A-4ED3-A5BC-6C3A74312F23](https://user-images.githubusercontent.com/9804078/81255195-e7f18480-8fe1-11ea-9817-2bec6526caa2.png)

**Comment by dennmuel** [comment]
Thanks for reporting @JonnyOThan! I provided a fix that should be in production soon. :)
