### ISSUE TITLE
Game breaks if you select “My card Sucks” more than one in 5 turns

### ISSUE THREAD

**Issue by phelantomas** [jakelauer/allbadcards#2]
The button to click My card sucks can still be pressed when you have previously selected within 5 turns. Then the game tells you can’t play it but doesn’t let you back

**Comment by jakelauer** [comment]
Can you describe this a bit more? The game is supposed to prevent you from hitting it if you wait fewer than 5 rounds.

**Comment by jakelauer** [comment]
No details, and I can't reporo this.
