### ISSUE TITLE
Translated version of at least some decks. It'd be great to have it in spanish and I'd love to help translating

### ISSUE THREAD

**Issue by gonsus** [jakelauer/allbadcards#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jakelauer** [comment]
I would love for you to take a stab at it! I haven't built in localization support in the UI yet but I would be more inspired to do so if there were translations!

**Comment by gonsus** [comment]
hey! How would you like me to help then? I'd be more than happy to
translate at least the main card pack :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jakelauer** [comment]
I'm going to call this closed, as we now support custom packs. Non-EN is a supported category
