### ISSUE TITLE
Can't Pick Two Cards!!!

### ISSUE THREAD

**Issue by cecomp64** [jakelauer/allbadcards#205]
Some cards require two answers, but alas, one cannot appropriately select two cards to play.  Don't even get me started about the order.

**Comment by dennmuel** [comment]
Thanks for reporting @cecomp64! Do you have some example cards at hand? I have a suspicion as for the reason (import from cardcast) but I can't tell just from the information you gave.

**Comment by jakelauer** [comment]
Found a couple issues that are fixed in 652d70006bcc7fac0ea39630241f7feda7054a15

**Comment by cecomp64** [comment]
Thank you for the quick fix! I’ll note which cards are affected if I see it again.
