### ISSUE TITLE
Server is kill

### ISSUE THREAD

**Issue by kinglozzer** [jakelauer/allbadcards#208]
apology for poor english

when were you when allbad.cards server dies

i was sat at home drinking brain fluid when fred ring

'server is die'

'no'

---

Cloudflare says:

> Error 520 Ray ID: 59051f4e8b4e0712 • 2020-05-08 18:07:47 UTC
Web server is returning an unknown error

Thanks for making this! I was having fun testing it out when the server went down (wasn’t me I swear), looking forward to using it with family & friends soon 😁

**Comment by jakelauer** [comment]
Haha, sorry about that! Not sure what went wrong but we're back.
