### ISSUE TITLE
Sharing games should be more straightforward

### ISSUE THREAD

**Issue by jakelauer** [jakelauer/allbadcards#21]
1. What URL was your game at?
NA
 
2. Describe the problem you experienced
When starting a game, the screen that shows the game ID makes it unclear how to get others to join the game.

3. Did you see any errors?
NA

4. Screenshots - If applicable, add screenshots to help explain your problem.
NA

5. Additional information
Please provide any additional helpful information, like:
NA

**Comment by CryoRig** [comment]
Maybe you could add QR Codes?
Scan the QR Code and prefill the textfield wuth the gameurl so that you only have to choose whom i want to invite
i don´t know if this works with any other messanger but for WhatsApp its easy:
https://faq.whatsapp.com/en/android/26000030/

**Comment by jakelauer** [comment]
I have swapped to human readable URLs to make this a bit more straightforward, plus improved the link copying experience.
