### ISSUE TITLE
Allbadcards - cannot select multiples

### ISSUE THREAD

**Issue by RavennaR** [jakelauer/allbadcards#211]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by RavennaR** [comment]
On allbadcards, in a group game, we could not select multiple cards on a "pick 2" prompt. Problem applied to all players, not just my guest account.

**Comment by jakelauer** [comment]
I believe this is fixed but I haven't deployed that did yet

**Comment by jakelauer** [comment]
Fix is deployed
