### ISSUE TITLE
all bad cards

### ISSUE THREAD

**Issue by pinkfla2** [jakelauer/allbadcards#212]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by dennmuel** [comment]
Hey @pinkfla2, thanks for contacting! Unfortunately, I cannot see any information on what your issue is about. Would you mind elaborating? Or was it just a mistake and this issue can be closed?
