### ISSUE TITLE
Possible SQL Injection?

### ISSUE THREAD

**Issue by PENTASHIFT** [jakelauer/allbadcards#213]
1. What URL was your game at?
https://allbad.cards/game/humid-jay-112

2. Describe the problem you experienced
Possible SQL (or whatever DB) Injection vulnerability? Used Username: Bobby Tables.

3. Did you see any errors?
See screenshot attached

4. Screenshots - If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/17925661/81463182-53675d80-916c-11ea-81ac-94f01d51c6c8.png)

5. Additional information
Please provide any additional helpful information, like:
- Firefox
- Debian 10

**Comment by jakelauer** [comment]
This is not an injection issue, but I did see it happening. I think it is a JavaScript issue causing no date to be sent to the server.
