### ISSUE TITLE
Feature card idea

### ISSUE THREAD

**Issue by timmathern** [jakelauer/allbadcards#214]
A stipper that can suck start a Harley

**Comment by timmathern** [comment]
Also a great card would be
I have a mangina

**Comment by haydius** [comment]
Hi @timmathern , the core game contains only the official _Cards Against Humanity_ and a selection of published third-party ones that have gained good traction in the community.
If you're looking to spice up the game with some custom cards of your own, try your hand at making your own deck over at [CardCast](http://cardcastgame.com) and then share the pack code with your friends ^_^

**Comment by jakelauer** [comment]
Now that CardCast shut down, you can create card packs right from ABC :)
