### ISSUE TITLE
Card elimination option during Czar's final winner selection phase

### ISSUE THREAD

**Issue by kevin-hoiland** [jakelauer/allbadcards#215]
As the Card Czar, after reading all answers and in final process of choosing the winner...

In order to help visually narrow down the choices (especially helpful when lots of cards) and also to build suspense for everyone else in the final set of possible winners...

It would be fun for the Czar during final selection to have an option of removing cards from everyone's view which are not in the Czar's top choice, for example sliding a card left/right to make it go away or an X icon on the side.  If desired the Czar could still just pick a winner whenever, but also optionally narrow down visible choices.

**Comment by dennmuel** [comment]
Thanks for your suggestion @kevin-hoiland! Looks to me like this feature has already been requested in #91, though I will leave it to @jakelauer to decide which issue to close since you elaborated a little more on the idea.

**Comment by kevin-hoiland** [comment]
Dang it, sorry about that, was a few margaritas deep last night and missed it 🤦 Anyway, great app, everyone loved it, fun times 🥳

**Comment by dennmuel** [comment]
All good, no worries :)
