### ISSUE TITLE
Tried to Join game and got the following message

### ISSUE THREAD

**Issue by callan-stretton** [jakelauer/allbadcards#216]
> The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

Appeared on iPhone 7 Plus Safari and Chrome - iOS 11.4.1 

Game URL: 
https://allbad.cards/game/balding-panda-9326 

This also happened when trying to 'Spectate', after refreshing, and trying with different names. 

Was able to get in using another device, an iPad. 

![3AB8FFD9-B0D3-469F-9D11-151CA5AC64AF](https://user-images.githubusercontent.com/29969836/81469281-59c30b80-9238-11ea-97be-7af440f69f27.jpeg)

**Comment by jakelauer** [comment]
This has been fixed!
