### ISSUE TITLE
CAH Chat

### ISSUE THREAD

**Issue by Reinsholm** [jakelauer/allbadcards#217]
My idea is...
A chat in the waiting room, would be nice. Just so you can ask the game owner to start the damn game, instead of ending up waiting forever.

**Comment by dennmuel** [comment]
Thanks for the suggestion @Reinsholm! I believe your idea has already been suggested. Would you be okay with closing this issue this in favor of #113?

**Comment by jakelauer** [comment]
Yeah, #113 dupe! Check that issue for future updates :)
