### ISSUE TITLE
Repeated card in a game

### ISSUE THREAD

**Issue by fabalcu97** [jakelauer/allbadcards#22]
BEFORE SUBMITTING:

1. What URL was your game at?
https://allbad.cards/game/RoDbmcjG9
2. Describe the problem you experienced
Repeated card: "Not having a reason to commit suicide" I think it was.
3. Did you see any errors?
No
4. Screenshots - If applicable, add screenshots to help explain your problem.
Didn't take one

**Comment by jakelauer** [comment]
Fixed! I hope.
