### ISSUE TITLE
Some sort of crash?

### ISSUE THREAD

**Issue by Aciho** [jakelauer/allbadcards#220]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/muted-marten-2930

2. Describe the problem you experienced
Long delay, followed by error popup

3. Did you see any errors?
 "Unexpected token < in JSON at position 0"

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
Chrome
- Device type
PC

**Comment by jakelauer** [comment]
Looks like a server had A CPU spike for about 20 minutes before recovering. I have added alarm behaviors to reboot this server if that happens in the future!
