### ISSUE TITLE
Problem with all the bad cards game

### ISSUE THREAD

**Issue by Gingerhotgirl** [jakelauer/allbadcards#221]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/funny-partridge-3199
. Describe the problem you experienced
Frozen all the time
3. Did you see any errors?
Yes 
4. Screenshots - If applicable, add screenshots to help explain your problem.
I dont have any 
5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
Looks like a server had A CPU spike for about 20 minutes before recovering. I have added alarm behaviors to reboot this server if that happens in the future!
