### ISSUE TITLE
https://not.allbad.cards/game/rustling-eel-633

### ISSUE THREAD

**Issue by Ciroso** [jakelauer/allbadcards#222]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://not.allbad.cards/game/rustling-eel-633
2. Describe the problem you experienced
Not working for all the party during card picking
3. Did you see any errors?

**Comment by jakelauer** [comment]
Looks like a server had A CPU spike for about 20 minutes before recovering. I have added alarm behaviors to reboot this server if that happens in the future!

**Comment by Ciroso** [comment]
Also, some time, during the card picking for the master, the game force back the counter mailing the master to ready the same card 2 or 3 time...but maybe is the cpu spikeIl 10 Mag 2020 00:27, Jake Lauer <notifications@github.com> ha scritto:
Looks like a server had A CPU spike for about 20 minutes before recovering. I have added alarm behaviors to reboot this server if that happens in the future!

**Comment by Ciroso** [comment]
Some time does not start the game when all ready in the lobby, my friends said that there was a problem "unexpected token...json..."Il 10 Mag 2020 02:45, arman.lagevardi@hotmail.com ha scritto:Also, some time, during the card picking for the master, the game force back the counter mailing the master to ready the same card 2 or 3 time...but maybe is the cpu spikeIl 10 Mag 2020 00:27, Jake Lauer <notifications@github.com> ha scritto:
Looks like a server had A CPU spike for about 20 minutes before recovering. I have added alarm behaviors to reboot this server if that happens in the future!
