### ISSUE TITLE
Bug with Allbad Card Game

### ISSUE THREAD

**Issue by rachnbob** [jakelauer/allbadcards#224]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
Allbad.cards/game

2. Describe the problem you experienced
Trying to start a new game 
Dialog box with the error message "Unexpected token < in JSON at position 0"

3. Did you see any errors?A
Unexpected token < in JSON at position 0

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type
Tried on Chrome on iPhone, Huawei and Samsung

**Comment by jakelauer** [comment]
Looks like a server had A CPU spike for about 20 minutes before recovering. I have added alarm behaviors to reboot this server if that happens in the future!
