### ISSUE TITLE
https://allbad.cards/game/slimmer-jay-5273

### ISSUE THREAD

**Issue by jsayram** [jakelauer/allbadcards#229]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/slimmer-jay-5273
2. Describe the problem you experienced
502 error gateway game stopped mid way with json exception
3. Did you see any errors?
502
4. Screenshots - If applicable, add screenshots to help explain your problem.
[image](https://user-images.githubusercontent.com/2413200/81488450-ec62ab00-9236-11ea-94ce-e8484bc9a23b.png)

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
One server had a 30 minute hiccup. I've put behavior in place to reduce this!
