### ISSUE TITLE
Time out for inactive player

### ISSUE THREAD

**Issue by kwininger91** [jakelauer/allbadcards#23]
My idea is... to have a timer for inactive players or the option to kick someone. We had someone stop the game because they were unable to leave the game when they stopped playing.

**Comment by wobblybobz** [comment]
Pretty sure this is already available. The Owner of the game can already boot someone in the game by clicking the Game Roster (Two People) Icon in the top right and then clicking the button to remove them on the right hand side of their name.

**Comment by jakelauer** [comment]
Yes, this already works as long as the owner is still around. If the game owner leaves you have to create a new game, but I think that scenario is fairly acceptable in comparison to the work it would be to add a kick/timeout function.
