### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by hex-trainer-eevee** [jakelauer/allbadcards#233]
Hello! I hosted a game so my boyfriend and I could play and chat over discord. We started with AI, which is great and they make great choices, and I let the game go public because I figured why not. The game came to a grinding halt when a new player to the game refused/couldn't pick a card. We both ended up leaving the game after about five minutes of waiting so that the card czar could make a choice but couldn't from the new player. If possible, something like adding a feature you can toggle on and off for a timer to cut off a player if they're taking too long. Essentially a skip function. I figure 45 seconds to a minute would be generous. Thanks!

**Comment by jakelauer** [comment]
Just added this tonight!
