### ISSUE TITLE
Didn't let anyone pick cards

### ISSUE THREAD

**Issue by hjoies** [jakelauer/allbadcards#238]
once I started the round as card czar it immediately picked cards for everyone and when to show me the cards.

https://allbad.cards/game/broker-otter-4133

Chromebook on chrome browser

P.S. I'm not sure if you can see all that happened in the game via the link but it was super glitchy.

**Comment by jakelauer** [comment]
Good catch, there was a bug with the new round timer. Should be fixed right about now!
