### ISSUE TITLE
One Card Czar Throughout

### ISSUE THREAD

**Issue by shawntempesta** [jakelauer/allbadcards#242]
Make it so there is one card czar so if we Facebook Live stream, the host can host, everyone else can play.

**Comment by shawntempesta** [comment]
As I said on that thread... Yep. Pretty much it. Rather than the winner becoming the czar, you'd have a master czar that would determine winning cards throughout. Best use case being live streams with contestants attempting to play to the humor of the czar. It's the one killer app that it's missing that could make this huge on Twitch/Facebook streams.

**Comment by jakelauer** [comment]
Maybe the best option would be to make the setting work so the owner is the permaczar. I'll prioritize this

**Comment by shawntempesta** [comment]
That would be amazing!

**Comment by shawntempesta** [comment]
Any luck on this? I am chomping at the bit to start using!

**Comment by jakelauer** [comment]
This is complete! You can now enable a setting so that the game owner is permanently the Card Queen.

**Comment by shawntempesta** [comment]
You freaking RULE! Can't wait. Thank you!
