### ISSUE TITLE
lost connection

### ISSUE THREAD

**Issue by bellebellebelle** [jakelauer/allbadcards#245]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/fluffy-locust-5291
2. Describe the problem you experienced
it kept saying id lost connection even after i reopened the browser and made a new game
3. Did you see any errors?
no
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser - Chrome
- Device type

**Comment by jakelauer** [comment]
Looks like a short blip but fixed now!
