### ISSUE TITLE
bug recieved when submitting a card

### ISSUE THREAD

**Issue by reubenlindroos** [jakelauer/allbadcards#246]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

https://allbad.cards/game/subjugated-donkey-9173

2. Describe the problem you experienced
Cant submit cards. Get error dialogue instead.

3. Did you see any errors?
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
chrome
- Device type
laptop (Dell G3)

**Comment by jakelauer** [comment]
I think this is fixed now
