### ISSUE TITLE
The "data" argument must be of type string of an instance of Buffer, TypedArray, or DataView. Received undefined

### ISSUE THREAD

**Issue by BurningDog** [jakelauer/allbadcards#247]
Thanks so much for this game! I've played it every Thursday night with friends for the last month (on our phones, using Zoom for banter), and it's been cool to see how you've added features over time. Last Thursday was the best experience so far (in terms of features and speed).

Unfortunately this week things are badly broken. It's not just one issue, there's a stack of issues. We had to create 3 different games; the first one stopped working for 3 out of 6 players; the 2nd one the host (me) couldn't start it (error screenshot below) and while the 3rd one worked, I had a number of small issues with it. Instead of detailing these all as separate bug reports, I'm assuming they're linked to one core issue, given that last week (and all times before that) everything was working fine.

In addition, this week felt a bit laggy...which _could_ be internet, but I haven't noticed that in the previous times I've played.

1. What URL was your game at?

We played 3 games and had issues with all of them.

* https://allbad.cards/game/traveled-grasshopper-539
* https://allbad.cards/game/mysterious-catfish-7768
* https://allbad.cards/game/worldwide-vulture-5751

2. Describe the problem you experienced

About 8 questions into the first game (6 players), one of the players got an error and couldn't proceed. 3 other players were fine. The error he got read,

```
The "data" argument must be of type string of an instance of Buffer, TypedArray, or DataView. Received undefined
```

I then created a new game, but couldn't start it because of the same issue showing up on my phone only, no-one else's (screenshot below).

Another player created a new game and everything worked fine, except for:

* One of the other players was the Card Czar; when she chose a winner all cards on the screen disappeared, it didn't show the winner...but after 30 seconds the next round started as per normal (with the correct score). This only happened once the entire game.
* I accidentally closed my tab and when I re-opened it, even though all of my cards were there none of the normal words on the card were (?!). I'm using dark mode. A refresh fixed it. (Sorry, forgot to screenshot).
* I accidentally closed my tab _again_; on re-open the countdown timer was wrong for me (showed 53 seconds left, when it was actually closer to 30 for everyone else).
* Near the end my "Play" button wouldn't work for about 15 seconds; it eventually worked. This only happened once.

3. Did you see any errors?

Yup - detailed above, and screenshot below.

4. Screenshots - If applicable, add screenshots to help explain your problem.

![WhatsApp Image 2020-05-14 at 21 54 44](https://user-images.githubusercontent.com/787653/81980850-a8edaf80-962f-11ea-8303-9aed83c63cd2.jpeg)

5. Additional information

I'm using Chrome version 81.0.4044.138 on Android 9, kernel 4.4.111-17979456 on a Samsung Galaxy A20.

**Comment by jakelauer** [comment]
This issue is related to the new security measures I put in. In short, clearing your cookies will probably fix this until the time I can implement a better fix.

**Comment by jakelauer** [comment]
I believe this is fixed

**Comment by BurningDog** [comment]
Yup, looks like it - thanks!
