### ISSUE TITLE
Wrong Amount of Answers

### ISSUE THREAD

**Issue by danohengeveld** [jakelauer/allbadcards#248]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/one-eyed-cattle-44

2. Describe the problem you experienced
Three answer showed up at a two blanks black card

3. Did you see any errors?
no

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
Chrome
- Device type
Windows 10

**Comment by dennmuel** [comment]
Hi @danohengeveld, thanks for reporting! Do you happen to remember the black card or some significant part of it?

**Comment by danohengeveld** [comment]
> Hi @danohengeveld, thanks for reporting! Do you happen to remember the black card or some significant part of it?

I am very sorry but I am afraid not.

**Comment by dennmuel** [comment]
Depends on whether @jakelauer can conjure something from the logs... No worries, next time you come across it, let us know :)

**Comment by jakelauer** [comment]
No dice without details :(
