### ISSUE TITLE
it won't let me start the game 

### ISSUE THREAD

**Issue by shodoe** [jakelauer/allbadcards#249]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
allbad.cards/game/mysterious-otter-59

2. Describe the problem you experienced
It won't let me start the game 

3. Did you see any errors?
It won't let me start the game 
4. Screenshots - If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/65379381/82004065-ebc47d00-9659-11ea-8806-20972c8cdec5.png)

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type
PC

**Comment by jakelauer** [comment]
Unforutnate side effect of server issues which are now fixed
