### ISSUE TITLE
Adding `n` blank/custom white cards to the deck

### ISSUE THREAD

**Issue by josh-hemphill** [jakelauer/allbadcards#250]
It'd be nice just mix in `n` number of blank/custom answer cards to the deck so you can control the percent chance or for that matter just add percent chance option.

**Comment by jakelauer** [comment]
One idea I had was just to give everyone a blank card all the time. Does that make it less fun? I've never played with blank cards so your feedback will be helpful!

**Comment by josh-hemphill** [comment]
Well I think part of the fun is being forced to answer with things more offensive than you would otherwise, so it really depends on the people you're playing with. 
I think you might want to limit it to max of 1 blank card at any time, and if you still use a percent chance, you could set it to 100% so that you always have one blank card if you want, but can adjust it. 
I might be worried about the intuitiveness of that option, but I would like the ability to have just a few blank cards for groups that might not be very good at using them.

**Comment by jakelauer** [comment]
This is done! You can now choose the "Allow write-ins" option, which will give every player one blank card.
