### ISSUE TITLE
Minor Typo in white card

### ISSUE THREAD

**Issue by Alpenglow88** [jakelauer/allbadcards#252]
Just a minor typo seen in one of the white cards. I own this deck and the card reads differently for me so just checking...

`server/data/third_party/packs/guards_against_insanity_ed_5.json` 

Line 128 should read

`"Acting out rape fantasies with strangers you're never met.",`

Instead of 

` "Actioning out rape fantasies with strangers you're never met.",`

**Comment by Alpenglow88** [comment]
Stand corrected - ignore my bug!

**Comment by haydius** [comment]
Actually there is a typo on [that line](https://github.com/jakelauer/allbadcards/blob/master/server/data/third_party/packs/guards_against_insanity_ed_5.json#L128), what a coincidence!

Should be `you've` rather than `you're`

**Comment by dennmuel** [comment]
Well, I see "Actiong" at the beginning of the line. I'll fix it. Thanks to both of you!
