### ISSUE TITLE
TYPO

### ISSUE THREAD

**Issue by alexsteady** [jakelauer/allbadcards#255]
Typo: Grump Cat should be Grumpy Cat

https://allbad.cards/game/patriot-gnu-4933

<img width="484" alt="Screen Shot 2020-05-15 at 5 43 43 PM" src="https://user-images.githubusercontent.com/29441545/82106105-e86dd780-96d3-11ea-84a8-d5288f844444.png">

PS: https://en.wikipedia.org/wiki/Andrew_Lloyd_Webber

**Comment by dennmuel** [comment]
Thanks @alexsteady, I'll fix it. Sorry, but I don't get the PS, though.
