### ISSUE TITLE
Cards autopicking before the card czar starts the round

### ISSUE THREAD

**Issue by hannahaurora13** [jakelauer/allbadcards#258]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/shaped-warthog-1844

2. Describe the problem you experienced
Cards autopicking before the card czar starts the round. No one had the chance to read the black card or submit options. The computer did everything itself

3. Did you see any errors?
No errors shown

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser---All players in Chrome
- Device type---All 3 players on laptops. 1 macbook, 1 toshiba (windows 10), 1 Dell (windows 10)

**Comment by jakelauer** [comment]
Hahaha, that's not good. I'll check it out! In the meantime, disabling the round timer should fix

**Comment by jakelauer** [comment]
Believe this is fixed
