### ISSUE TITLE
Cardcast Shutting Down - Discussion / Alternatives

### ISSUE THREAD

**Issue by haydius** [jakelauer/allbadcards#261]
With CardCast shutting down (such a massive blow to the system) I know there will be some tickets logged for the broken/missing functionality so I'm dropping this here as a placeholder / hub for discussion.

Some starter ideas...

**CSV/TXT upload**
Give a specified format and allow upload of custom card decks (persistent or prer game)

**Build a deck**
Add new site functionality allowing users to build and store custom decks

In both cases, may need to impose size limitations to prevent excessive data use or overhead.

Also sanitise ~your hands~ the users inputs to prevent issues.

If a similar functionality as CardCast decks is achieved, may gain a community of users willing to support it (via code or funding) given the hole left by CardCast

**Comment by dennmuel** [comment]
Just thinking out loud here...

With limitation to people knowing how to use git, one could think about adding custom decks via git submodules. E.g. people would have repo for their own deck (in csv, txt, json, whatever) and would aks for them to be included in the allbadcards repo as a submodule.

If the deck is updated, the creators can ask for the newest state (commit/tag) to be checkout in the submodule. That keeps curation of a deck in the hands of the creators, but also provides some form of control as to what changes are taken into the allbadcards core.

**Comment by jakelauer** [comment]
My best plan for this is to essentially replicate CardCast functionality but on ABC.

Also, sidenote, I have a copy in my Redis instance of all the CardCast packs that were used in ABCs. So if anyone used theirs and wants their copy, I can make that happen.

**Comment by dantherussell** [comment]
The JSON formatting you've used for your built in decks looks very powerful as it is, allowing for people to upload custom sets that way could be good

**Comment by jakelauer** [comment]
As of a few minutes ago, All Bad Cards now supports custom card packs. Coming soon - upload of the JSON files that we provided when exported from our CardCast tool.

https://allbad.cards/packs :)

**Comment by jakelauer** [comment]
Heads up - JSON upload is now implemented.
