### ISSUE TITLE
Accounts to hold settings

### ISSUE THREAD

**Issue by lionsmaneprod** [jakelauer/allbadcards#264]
Every time my friends and I come to play, I have to go through and change settings to build the game we want. I'd love to be able to login with an account where my favorite settings are already set as a preference, and just launch a game.  Thanks for the consideration.

**Comment by jakelauer** [comment]
Accounts now exist - just gotta make settings :)

**Comment by lionsmaneprod** [comment]
Brilliant

**Comment by lionsmaneprod** [comment]
Two questions.. My hope was to be able to SAVE a GAME with my custom settings so when we want to play, I just open that game and we're off and running.  Is this possible?  Also, how do you create the empty space in the black card to be filled by the white card answer?  The editor only allows me to enter a single underscore character "_"  instead of multiples "_______"  ...

**Comment by jakelauer** [comment]
Accounts will be able to save preferred game settings in a future updates. For now, accounts are only for creating card packs.

When you create your custom cards, you will only use a single underscore for each fillable blank. When you play using the packs, they will display with larger blank spaces.

**Comment by lionsmaneprod** [comment]
Great to know. Appreciate the great work.
