### ISSUE TITLE
Previous round winner

### ISSUE THREAD

**Issue by Roild** [jakelauer/allbadcards#268]
The ability to see all the options on the previous round and the winner.

**Comment by jakelauer** [comment]
You can see the round winner after each round. You can also change game options from the gear in the top right.

**Comment by ThiefMaster** [comment]
I think what OP meant was being able to see all the options even after the card queen selected a winner and the next round started. For example, if you play your card and then go AFK for a moment, but want to see what cards were played and which one won..

**Comment by Roild** [comment]
That is indeed what I mean. I was likely vague on my first post. I didn't explain myself properly. It would be nice to see the previous winner as well as all the cards that each player presented on the previous game. I'm checking the game now and the game options from the gear in the top right does not allow "see previous cards (with winner)" or anything like it to be present in the game. Yeah, it'd be great for anyone who goes AFK or just isn't putting complete attention to the game. Thank you.
