### ISSUE TITLE
Join with a code

### ISSUE THREAD

**Issue by DanLauer** [jakelauer/allbadcards#27]
Nav to the the main URL, then join with just a code.

**Comment by jakelauer** [comment]
Hi! The issue with this is creating a code so short that it's easy to understand without having it sent to you. Jackbox gives a 4-character code which requires clearing out old codes periodically, whereas my system is guid-based and does not need to be cleared for reasons besides performance.

**Comment by jakelauer** [comment]
This is done :) https://allbad.cards/games
