### ISSUE TITLE
'Received undefined'

### ISSUE THREAD

**Issue by prissyy** [jakelauer/allbadcards#272]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/

2. Describe the problem you experienced
Pop up saying "The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined"

3. Did you see any errors?
No except above pop up

4. Screenshots - If applicable, add screenshots to help explain your problem.
![Screen Shot 2020-05-18 at 12 25 42 am](https://user-images.githubusercontent.com/65502158/82154077-359da500-989e-11ea-942d-f45a5ece20f2.png)

5. Additional information
Please provide any additional helpful information, like:
- Browser
Google Chrome
- Device type
Macbook Air

**Comment by jakelauer** [comment]
I believe this is now fixed!
