### ISSUE TITLE
Custom Cards

### ISSUE THREAD

**Issue by prolongedeyecontact** [jakelauer/allbadcards#273]
You’ve probably had this a lot but since that other website closed down, it’d be a super cool idea for you to find a way to do custom card packs. I’d love to make cards for me and my friends to play.

**Comment by bnexd** [comment]
If you had card packs at cardcast and used them at allbadcards you can export the json file at https://allbad.cards/cardcast-export

**Comment by dennmuel** [comment]
Thanks for the suggestion! There is already a discussion about this in #261 , so I'm closing this, if you don't mind. :)
