### ISSUE TITLE
Error on selecting answer

### ISSUE THREAD

**Issue by IngMalva** [jakelauer/allbadcards#274]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://not.allbad.cards/game/hot-button-tarsier-8738

2. Describe the problem you experienced
Error on selecting any answer. No further action possible. No refresh/relog works.

3. Did you see any errors?
request to https://api.cardcastgame.com/v1/decks/null failed, reason: getaddrinfo ENOTFOUND api.cardcastgame.com

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Chrome  81.0.4044.138
- PC

**Comment by bnexd** [comment]
cardcast got shut down. I think the every api request to cardcast will not work

**Comment by jakelauer** [comment]
Yeah, @bnexd is right :(

**Comment by IngMalva** [comment]
That's unfortunate. 
Thank you for your replies!

**Comment by jakelauer** [comment]
@IngMalva Yep! Due to CardCast shutting down, All Bad Cards now has a custom pack creator and browser :)
