### ISSUE TITLE
Deck issue

### ISSUE THREAD

**Issue by Kinj1** [jakelauer/allbadcards#279]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/unassisted-peafowl-753
2. Describe the problem you experienced
I tried to play with a old custom deck but it don't work

3. Did you see any errors?
Yes, I did.

4. Screenshots - If applicable, add screenshots to help explain your problem.
https://i.imgur.com/6URmRQj.jpg
5. Additional information
Please provide any additional helpful information, like: 
- Browser Google Chrome
- Device type PC

**Comment by jakelauer** [comment]
Custom packs are not supported because CardCast shut down.
