### ISSUE TITLE
Custom cards disappear

### ISSUE THREAD

**Issue by Eliderad** [jakelauer/allbadcards#280]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/packs

2. Describe the problem you experienced
Cards disappear when trying to edit a custom pack, and saving after editing means they're gone, but they still seem to be there if I don't actually open for editing.

3. Did you see any errors?
No.

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Chrome, Windows 10
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
Fixed! The cards were not actually lost, just a caching issue :)
