### ISSUE TITLE
Dark Mode Colors

### ISSUE THREAD

**Issue by CalebMcPherson** [jakelauer/allbadcards#281]
My idea is...

The Text Color on the Dark mode light cards is very hard to read. Would it be possible to change this to a darker color?

**Comment by jakelauer** [comment]
Can you give an example of where in the site you are seeing this?

**Comment by CalebMcPherson** [comment]
Yeah, sorry for the delay. It's the white cards while setting the game to dark mode for me. I'm seeing this in Edge and Chrome. 

![Annotation 2020-05-20 202330](https://user-images.githubusercontent.com/55310889/82513169-ce6b3500-9ad7-11ea-93c1-5f9fba5177f6.png)

**Comment by jakelauer** [comment]
Fixed in 967d8bbc8c26357318274db79e1967ccc913022b
