### ISSUE TITLE
Undefined "Game Queen"

### ISSUE THREAD

**Issue by outfeeder** [jakelauer/allbadcards#283]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/grande-shrew-6687

2. Describe the problem you experienced
The game doesn't seem to be registering that I'm still in the game, instead searches for an undefined "Game Queen". Refreshing, leaving the game and rejoining it, as well as starting a new game haven't appeared to fix the error. 

Also- in Dark mode, the text on white cards appears white

3. Did you see any errors?
Nope

4. Screenshots - If applicable, add screenshots to help explain your problem.
http://prntscr.com/skuhui

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type
Google chrome, windows 10 on a Toshiba Satellite

**Comment by jakelauer** [comment]
Good find. This was due to an order of operations issue with the logic! Today I learned where modulus goes in PEMDAS... Or should I say PEMMDAS
