### ISSUE TITLE
Getting 'Cannot read property 'packId' of undefined'

### ISSUE THREAD

**Issue by KilianTep** [jakelauer/allbadcards#285]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://not.allbad.cards/game/roomful-cat-8641?fbclid=IwAR2Io8JtT-phYTxmNkPd6q03i6nX27q_RVc8QysMt4n9mXBHANu6qP4Vgik

2. Describe the problem you experienced
When clicking on the **START NEXT ROUND** button, I got a 
_Cannot read property 'packId' of undefined_
3. Did you see any errors?
_Cannot read property 'packId' of undefined_

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser: Google Chrome
- Device type: MacBook Pro

**Comment by jakelauer** [comment]
I believe this is now fixed by a check which determines whether your card packs have enough cards.
