### ISSUE TITLE
Json error: unexpected "<" at position 0. 

### ISSUE THREAD

**Issue by Audrey-Randall** [jakelauer/allbadcards#286]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by Audrey-Randall** [comment]
URL: https://allbad.cards/game/acquainted-shrimp-7781

When clicking on "start the next game" or "pick the winner," a pop-up appears with something like that error. When inspecting the code of the page, this error seems to be preceded by "Failed to load resource: the server responded with a status of 502." I'm afraid I didn't get a screenshot. I'm using Chrome on Windows 10.

**Comment by jakelauer** [comment]
I think this is now fixed!
