### ISSUE TITLE
JSON error ALL...THE..TIME

### ISSUE THREAD

**Issue by redpelon** [jakelauer/allbadcards#287]
tonight, seems to be happening every time we click a button.  so annoying, ruined our evening

![Screenshot 2020-05-21 at 10 47 23 PM](https://user-images.githubusercontent.com/65751786/82631071-3f831900-9bba-11ea-8c2a-7502060a3b2a.png)

**Comment by jakelauer** [comment]
Something went wonky with the servers. I believe it is fixed now!

**Comment by redpelon** [comment]
Holy dang dude, you are the fastest response I have ever received!  Upvote
to you! (reddit reference)
