### ISSUE TITLE
Owner can start game without other players

### ISSUE THREAD

**Issue by dennmuel** [jakelauer/allbadcards#288]
1. What URL was your game at?
https://allbad.cards/game/wheeled-squirrel-617

2. Describe the problem you experienced
Out of curiosity I started a game, although I was the only participant and it worked. It shouldn't have worked, right?

3. Did you see any errors?
Nope.

4. Screenshots - If applicable, add screenshots to help explain your problem.
![grafik](https://user-images.githubusercontent.com/21078769/82676016-f9739700-9c45-11ea-8553-1d9832fde151.png)

5. Additional information
Please provide any additional helpful information, like:
- Browser: Firefox ESR
- Device type: Notebook

**Comment by dennmuel** [comment]
I also could start a game with only AI players besides me: https://allbad.cards/game/recycled-armadillo-765
And the worst thing about it: I was always the card queen! :laughing:

**Comment by jakelauer** [comment]
This is actually intentional. It's useful for testing custom packs!
