### ISSUE TITLE
Allow adding AI players after game starts

### ISSUE THREAD

**Issue by Barnickal** [jakelauer/allbadcards#289]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/pretty-snail-7263

2. Describe the problem you experienced
So I foolishly started a game with just one other player hoping others would join. She was queen... I chose my card, then was waiting ages for her to pick me as winner....Eventually kicked her to move on, which made me the queen and only player.... I clicked show me the cards and then there was no "Pick a winner". Couldn't move on.

3. Did you see any errors?
See above

4. Screenshots - If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/51230507/82675444-b82ab980-9c3c-11ea-91dd-0efe7f6b64ed.png)

5. Additional information
Please provide any additional helpful information, like:
- Browser - Chrome
- Device type - Windows 10 PC

**Comment by jakelauer** [comment]
I think the only solution here would be to make it possible to add AI players after you start. Not sure what else could be done here?

**Comment by Barnickal** [comment]
Maybe if a game is running and only one person is left, an AI is added automatically? Maybe the name shows that it's an AI? I say this with no idea of the work involved, so please ignore me if it's too much.

**Comment by gregx1337** [comment]
I was thinking in terms of the game perhaps displaying some links/buttons when an "only one player" status is detected, such as:
- Discard the current game entirely and force a quit/reset back to the original starting screen
- Add an AI player and continue (as mentioned above)
