### ISSUE TITLE
Unable to swap out crappy cards

### ISSUE THREAD

**Issue by kwininger91** [jakelauer/allbadcards#29]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

https://allbad.cards/game/3cjZ2icm8
2. Describe the problem you experienced
Multiple users were unable to replace their cards
3. Did you see any errors?
No errors
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
-

**Comment by jakelauer** [comment]
I couldn't reproduce this - it appears to be functioning correctly (can only swap out every 5 rounds)
