### ISSUE TITLE
Public backup of custom card sets

### ISSUE THREAD

**Issue by ThiefMaster** [jakelauer/allbadcards#291]
Assuming the cardcast decks are lost for good (I still hope they can release a dump at some point e.g. on archive.org, but who knows), this is something that should ideally never happen again.
But with a single person/company having the only database of cards, there's always the risk that a stupid lawsuit or simply change of interests, or a buy-out of the project by some company results in things shutting down or becoming restricted.

So what about making custom card sets inherently public, without the need to hammer your API for crawling them? A repo here on GitHub could be an option and it could even be automated!
Like this people could easily create decentralized backups by cloning the Git repo, so the data would be safe from lawsuits.

For the single-branch option I could imagine a structure like this (assuming there are two packs `pPwmQe1ME` and `6LeVPVGtU`):

```
/sets/p/pPwmQe1ME.json
/sets/6/6LeVPVGtU.json
```

Whenever changes to a custom set are made (or daily as a cronjob), the files in the repo would then be updated automatically.

If this is something that sounds interesting to you, I could probably have a look and send a Pull Request.

**Comment by jakelauer** [comment]
My main issue with this is that you have the option to make your pack private.

**Comment by ThiefMaster** [comment]
Those could be skipped during sync (doesn't make sense to sync private packs to a public repo ;))

**Comment by jakelauer** [comment]
I don't think this is feasible right now.
