### ISSUE TITLE
Lost Connection

### ISSUE THREAD

**Issue by caliclia** [jakelauer/allbadcards#296]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/outlaw-panda-1827?fbclid=IwAR2H86LzwKMoYOlf_WWaAaR5TnXvbB1BXK9xFO6siBAdQGq5CRfvY2gbGwg

2. Describe the problem you experienced
Continual Lost connection

3. Did you see any errors?
Lost Connection

4. Screenshots - If applicable, add screenshots to help explain your problem.
"Lost Connection
You have lost your connection to the server. Please check your connection, or retry. The most common reason for this to happen is switching tabs or leaving your browser for a while.

If this behavior continues, please click here to report it."

5. Additional information
Please provide any additional helpful information, like:
- Browser: Chrome
- Device type: MacPro

**Comment by jakelauer** [comment]
Intermittent server issues, now fixed!
