### ISSUE TITLE
Missing instructions on how to self-host

### ISSUE THREAD

**Issue by jtrees** [jakelauer/allbadcards#3]
Thanks a bunch for making this public. I would like to self-host it but can't find any instructions on what dependencies are required, how to set things up etc. Any chance you could add more details to the readme?

**Comment by jakelauer** [comment]
I'll definitely get this going. Thanks! The code is fairly specific to my domains at the moment.

**Comment by wumb0** [comment]
and it runs on windows? 
no judgement, but some judgement ;)

**Comment by archer007** [comment]
I would really appreciate build instructions and a dockerfile!

**Comment by jakelauer** [comment]
Done

PS - this now runs on Linux just fine.
