### ISSUE TITLE
One player's white card is blank at random each round 

### ISSUE THREAD

**Issue by insectatorious** [jakelauer/allbadcards#30]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/BW2CFDclW

2. Describe the problem you experienced.
When cycling through the cards to find a winner, one card at random was blank (regardless of whether two cards or one card was played). At the end when choosing the winning card, the card was visible. 

3. Did you see any errors?
No.

4. Screenshots - If applicable, add screenshots to help explain your problem.
https://imgur.com/a/d61QL1q

5. Additional information
Please provide any additional helpful information, like:
- Browser: Chrome 
- Device type: Mac

**Comment by jakelauer** [comment]
Fixed!
