### ISSUE TITLE
Game kicked us out

### ISSUE THREAD

**Issue by DKdoesData** [jakelauer/allbadcards#302]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/slanting-armadillo-8820

2. Describe the problem you experienced
Bad Gateway, kicked us out midgame
3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser multiple
- Device type, tablet, phone and macbook

**Comment by jakelauer** [comment]
This was due to a server problem due to high load that I believe is fixed now
