### ISSUE TITLE
Add a soundtrack while picking card

### ISSUE THREAD

**Issue by ialhashim** [jakelauer/allbadcards#31]
My idea is to assign a youtube clip that loops (e.g. the jeopardy song) while players pick cards.

**Comment by jakelauer** [comment]
The main issue I have with this idea is that the site is sort of built for video chat / audio chat. If everyone's devices start playing audio over the chat, it will sound crazy!

**Comment by ialhashim** [comment]
Thats a good point. I guess deciding the streams and input and output devices will be a mess. I was thinking of a similar scenario that sorta work, the Jackbox party games.

**Comment by jakelauer** [comment]
I will keep it in mind if I build out some Chromecast functionality :)
