### ISSUE TITLE
Multiple Scrapped Hands Caused Problem

### ISSUE THREAD

**Issue by raysalemi** [jakelauer/allbadcards#312]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/average-sloth-849

2. Describe the problem you experienced
Multiple players scrapped their hands in the same round. When I chose a winner the screen went blank and I had to refresh the page. 

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
I don't believe this bug was due to multiple scrapped hands. I think it was just a temporary issue.
