### ISSUE TITLE
Broken login on not.allbad.cards

### ISSUE THREAD

**Issue by raysalemi** [jakelauer/allbadcards#313]
There is a bug trying to login through Patreon on not.allbad.cards. When you try to accept letting Patreon get data you get this error:

{“message”:”The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.”,”stack”:”Error: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.\n    at getAuthError (/var/app/current/output/server/server.js:77163:15)\n    at /var/app/current/output/server/server.js:77311:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)”}

**Comment by raysalemi** [comment]
If you deny you get this error

{“message”:”Missing code, unable to request token”,”stack”:”TypeError: Missing code, unable to request token\n    at CodeFlow.getToken (/var/app/current/output/server/server.js:77654:27)\n    at _Auth.<anonymous> (/var/app/current/output/server/server.js:41066:53)\n    at Generator.next (<anonymous>)\n    at /var/app/current/output/server/server.js:41024:71\n    at new Promise (<anonymous>)\n    at __awaiter (/var/app/current/output/server/server.js:41020:12)\n    at _Auth.storeUserToken (/var/app/current/output/server/server.js:41064:16)\n    at /var/app/current/output/server/server.js:77015:31\n    at Generator.next (<anonymous>)\n    at /var/app/current/output/server/server.js:76995:71”}

**Comment by jakelauer** [comment]
Another good catch!
