### ISSUE TITLE
bug when players were kicked down to 2

### ISSUE THREAD

**Issue by Oakrin** [jakelauer/allbadcards#315]
1. https://allbad.cards/game/huddled-marten-1026
2. when the game was down to 2 players it crashed.
3. yes
4.
![Screenshot_2020-05-25 LucyHasAnxiety's game All Bad Cards](https://user-images.githubusercontent.com/32417109/82849354-5a040d80-9eac-11ea-9086-e92be267d06a.png)

5. Additional information
Please provide any additional helpful information, like:
- Firefox
- PC

**Comment by jakelauer** [comment]
This should be fixed now.
