### ISSUE TITLE
Elastic Beanstalk Deployment

### ISSUE THREAD

**Issue by jgrifft** [jakelauer/allbadcards#316]
My idea is...add variables to your EB deployment so those deploying in their own environment can select things like VPC, Security Group, Load balancers et.

**Comment by jakelauer** [comment]
Where even is this in the configuration? And what would you recommend?

**Comment by jgrifft** [comment]
Wasn't sure if it was something you were doing or not but I saw the .ebextensions and a few other references to Elastic beanstalk in the repo.  It's a good way to deploy on AWS.  I would suggest VPC, Security Group, instance Size, Load Balancer to start.

**Comment by jakelauer** [comment]
Yeah, I'm using Beanstalk for sure. Just curious how you know about the T3s?

**Comment by jgrifft** [comment]
I tried using elastic beanstalk to launch the repo.  In Elastic Beanstalk you can see and modify (to some extent) the settings for your environment.  That's how I saw the T3s.  Edited the comment because I wasn't really sure if that was something you were using or just the default for the AMI.  It's been a while since I've used EB.

**Comment by jgrifft** [comment]
I would move at least to a M class instance type.  No shared CPU, better network performance and not terribly more expensive than the T3s.  

The other suggestions were more of putting them in as variables rather than hiding them.  That way you don't have to reveal what you're using but others can deploy a bit more easily.  The VPC one is a big one for me since I don't have a default VPC in my account so I can't even attempt to deploy.

Docker would be great but I don't have any experience developing for it either so I'm hoping someone smarter than myself can help us out there.

**Comment by jakelauer** [comment]
AFAIK, people can do whatever they want with their own Beanstalk deployment. My code contains no configuration for this, so it's up to you if you want to do it.
