### ISSUE TITLE
Multiple instances of the same white card

### ISSUE THREAD

**Issue by lionsmaneprod** [jakelauer/allbadcards#319]
1. What URL was your game at?
>>>>oooo don't remember and have closed the browser. We were playing ONLY a single custom deck though.

2. Describe the problem you experienced
>>>>When revealing the white cards, two of us playing had the identical white card. There is only one instance of this card in the deck.

3. Did you see any errors?
>>>>No errors relative to THIS bug - though Safari users tend to get tons of script errors (just as a side note in general)

4. Screenshots - If applicable, add screenshots to help explain your problem.
>>>>Should have gotten one. Did not.  Sad panda.

5. Additional information
Please provide any additional helpful information, like:
>>>>I'm using Chrome on Windows 10

**Comment by jakelauer** [comment]
Was the deck you were using very big? If the deck doesn't have enough cards for everyone, it will reset.

**Comment by lionsmaneprod** [comment]
75 white cards, and I’m adding more – this was a test run of the deck. It seems to me the logic would preclude any player from having the same white cards as any other player since the physical game only has one white card with a given answer on it. Yes?

After the white card is used I suppose it makes sense it could end up in another player’s stack – but just not at the same time?

**Comment by jakelauer** [comment]
It depends on how many players you have. For example, with a 75 card deck and 6 players - you deal 60 cards per player. After 3 rounds, you've used up all your white cards and the deck resets, meaning all cards are now back in play.

I suppose the sound logic here would be to put all of the white cards back in play *except* the ones that are already in players' hands.

**Comment by lionsmaneprod** [comment]
Well we only had 3 players, and towards the end, almost all of us had hands full of white cards we had seen before.  Clearly we need to add more white cards, and I do plan to do that.

**Comment by jakelauer** [comment]
Do you think the behavior you saw matches what I said above, or do you think there is something else broken?

**Comment by lionsmaneprod** [comment]
When I think about how the original game is played, after white cards are submitted in hand, they go back into the stack, but like at the bottom or something, so they don't show up immediately (I think). Obviously the cards made available to the players are randomized so I guess that's fine. Ultimately I guess what I wasn't expecting was that the same card might show up in someone else's hand.
