### ISSUE TITLE
Can't get a game started because all my players keep losing connection

### ISSUE THREAD

**Issue by AlexReynard** [jakelauer/allbadcards#320]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at? - https://allbad.cards/game/stubborn-sand-dollar-1578

2. Describe the problem you experienced - Trying to put together a game. I can't stay the owner because every few minutes the game kicks me out. Same for everyone else. This is happening way too often. I even specifically added the site to my tab suspender whitelist AND turned off the idle timer in game.

3. Did you see any errors? - "Lost Connection
You have lost your connection to the server. Please check your connection, or retry. The most common reason for this to happen is switching tabs or leaving your browser for a while.

If this behavior continues, please click here to report it."

4. Screenshots - If applicable, add screenshots to help explain your problem. -  https://i.imgur.com/7gv9v2x.png

5. Additional information
Please provide any additional helpful information, like:
- Browser - Firefox and Chrome
- Device type - Desktop computer and laptops

**Comment by jakelauer** [comment]
This is the behavior meant to kick idle players but it's misbehaving. Did this happen before the game starts? I assume you were switching tabs and stuff?

**Comment by jakelauer** [comment]
Fixed now.

- Fixed idle behavior causing issues for normal games starting
- Idle timer only kicks players automatically in public games
- Idle timer marks players as idle in private games

**Comment by AlexReynard** [comment]
Oh, awesome! That was incredibly quick! 😄

________________________________
