### ISSUE TITLE
It will not start next round

### ISSUE THREAD

**Issue by Vivi12601** [jakelauer/allbadcards#321]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://not.allbad.cards/game/broiled-goat-8190
2. Describe the problem you experienced
would not start next round, kicked people out 
3. Did you see any errors?
yep, cannot reach property pack id undefined
4. Screenshots - If applicable, add screenshots to help explain your problem.
n/a
5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
This should be fixed
