### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by lionsmaneprod** [jakelauer/allbadcards#325]
1. What URL was your game at?
https://allbad.cards/pack/detail/QfYmzDZ9r  (not a game, editing a custom card pack)

2. Describe the problem you experienced
>>>>Random error cropped up while editing custom card pack. Wasn't doing anything at that moment, just looking at the screen when the error occured.

3. Did you see any errors?
>>>>> Unexpected token < in JSON at position 0

4. Screenshots - If applicable, add screenshots to help explain your problem.
>>>>>none

5. Additional information
Please provide any additional helpful information, like:
Chrome Version 83.0.4103.61 (Official Build) (64-bit) on Windows 10

**Comment by jakelauer** [comment]
This can happen when there are intermittent server problems.
