### ISSUE TITLE
Can't submit picks

### ISSUE THREAD

**Issue by williamschmitt21** [jakelauer/allbadcards#328]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/sharp-echidna-6336/play
2. Describe the problem you experienced
No one in the room could submit a pick.
3. Did you see any errors?
No.
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
Multiple browsers
- Device type
Multiple devices

**Comment by jakelauer** [comment]
It looks like the problem here was the COVID-19 pack: https://allbad.cards/pack/detail/aCAnoBPm1

Whoever created this pack added multiple blanks for the card you were on, so it was actually a pick-3 instead of a pick-1
