### ISSUE TITLE
Pick multiple cards for one

### ISSUE THREAD

**Issue by altheavlive** [jakelauer/allbadcards#329]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at? https://allbad.cards/game/geologic-sparrow-8562/play

2. Describe the problem you experienced: one card needed and was asking for multiples of either an extra one or two

3. Did you see any errors? no 

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser Mozilla Firefox
- Device type PC

**Comment by jakelauer** [comment]
No card was noted, so I can't know which one to fix.
