### ISSUE TITLE
No active card czar - had to abandon game

### ISSUE THREAD

**Issue by insectatorious** [jakelauer/allbadcards#33]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/BW2CFDclW

2. Describe the problem you experienced
2 players left the game. I (as the owner) removed them from the list of players (clicking on the players icon on the top right and then. selecting the player minus icon for each player). However it appeared that the card czar after picking the winner had already start the next round and the new card czar was one of the leaving players resulting in the game being stuck in a limbo state without a card czar and us (even me the Owner) unable to change the czar. 

3. Did you see any errors?
No.

4. Screenshots - If applicable, add screenshots to help explain your problem.
https://imgur.com/a/r07Rnuv

5. Additional information
Please provide any additional helpful information, like:
- Browser: Chrome
- Device type: Mac

**Comment by jakelauer** [comment]
Owner can now kick the czar. If this happens, the owner becomes the new czar.
