### ISSUE TITLE
Game Locks Up and shows various errors

### ISSUE THREAD

**Issue by spicecake68** [jakelauer/allbadcards#330]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

https://allbad.cards/game/amorphous-hare-1783/play

2. Describe the problem you experienced

Game will lock up for other players.  Random moments of game play.  It does seem to throw an error.  

3. Did you see any errors?

Yes.  Not on my screen, but it said something like "an error occurred, please refresh."  And whenever the player did this, they player could not resume game play without losing game progress, and they must come in with a new nickname.  I (running the room) had to boot the frozen player.  

4. Screenshots - If applicable, add screenshots to help explain your problem.

n/a

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

Chrome running on a Windows machine.  Not sure what the other players were running.  I think a  Mac environment.

**Comment by jakelauer** [comment]
Unfortunately, without screenshots, I am not sure if I can diagnose this. There is no such error message thrown in the code :(
