### ISSUE TITLE
Wrong player wins if "Rounds to Win" value reduced mid game

### ISSUE THREAD

**Issue by eric2071** [jakelauer/allbadcards#333]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
- https://allbad.cards/game/remorseless-ibex-9176
2. Describe the problem you experienced:
-Players had scores of 7, 5, 3, etc. and Rounds to will was set to 9. When rounds to win was reduced to 5, player with 5 points won despite not having the highest score.

3. Did you see any errors?
-No
4. Screenshots - If applicable, add screenshots to help explain your problem.
-N/A
5. Additional information
Please provide any additional helpful information, like:
- Chrome
- Android

**Comment by haydius** [comment]
@eric2071 
Ideally the rounds to win should not be reduced below the current highest score but good find.

@jakelauer 
Currently, [GameManager.ts, Line 745](https://github.com/jakelauer/allbadcards/blob/master/server/Engine/Games/Game/GameManager.ts#L745) finds the first available player with a score equal to or above the Rounds to Win value. Depending on the order of players in the list this may select the wrong winner as per issue described.

I'll try and write a PR for this now but something like this may work...

```javascript
//dummy array of players with scroes
const playersTest = [
  {name: 'Billy',score: 10},
  {name: 'Ray',score: 7},
  {name: 'Cyrus',score: 5},
];
// Pick the player with highest score
const winner = playersTest .reduce((prevVal,curVal) => {
  return prevVal.score < curVal.score ? curVal: prevVal;
})
console.log(winner.name,winner.score); // Billy, 10
```

Then have it check if player score is equal to or more than the rounds to win.
