### ISSUE TITLE
I am trying to play a game on allbadcards.com For cards against humanity.  However, when we start the game, The queen sees the black cards but nobody gets the white cards.  

### ISSUE THREAD

**Issue by DSM8675309** [jakelauer/allbadcards#335]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
I need a game link to check this out

**Comment by DSM8675309** [comment]
allbad.cards/game/immense-louse-4065

**Comment by jakelauer** [comment]
I joined the game but it says it's waiting for Daniel to pick the winner

**Comment by DSM8675309** [comment]
But nobody can see the white cards

**Comment by DSM8675309** [comment]
I see no cards to pick a winner

**Comment by DSM8675309** [comment]
Should I try a new game?

**Comment by jakelauer** [comment]
You can't see your white cards while the card queen is picking a winner

**Comment by DSM8675309** [comment]
But nobody ever got the white cards when we joined.
Let me start a new game and see if you can help me trouble shoot

**Comment by jakelauer** [comment]
Probably, I'm not sure what's happening to you. I just tried a game and it worked fine. I would need screenshots and stuff like it tells you when you file bugs
