### ISSUE TITLE
Export custom card pack to json

### ISSUE THREAD

**Issue by funnisquares** [jakelauer/allbadcards#336]
An option to export the card pack to json. Me and my friends are building quite the extensive card pack, but managing such a large deck with only the allbadcards tools is cumbersome (hard to find duplicates, or specific cards to edit for example). If It was possible to export the pack to json, so that it can be edited outside of the site, and then imported back in, would be a great feature!

**Comment by haydius** [comment]
Could try something like this as a starting point: [Google Sheet for AllBad.Cards JSON Export](https://docs.google.com/spreadsheets/d/17g8-iae-YqGUszvzpLF2HbHe6TsT6RgqFtmoDzlUFXs/edit#gid=1890525329)
Google Sheets has good collaboration skills to allow several people to update it. I'm not sure if the way the AllBad.Cards editor is set up allows you to upload and overwrite so you can maintain decks externally but that may be another feature ticket to log.
I haven't yet checked the JSON format for import as this was originally designed based around the JSON structure of the pre-existing CAH decks in the base code before being removed.
Would be an easy start

**Comment by dennmuel** [comment]
The following might be interesting if you already have your cards in e.g. a text file:

I wrote a [little bash script](https://github.com/dennmuel/custom-packs/commit/8b20ef8b47417c7eb1fecf6fa94aba4ffee8d54e) once to convert a line separated text file of black cards to a block of json. (Converting a file with white cards should be quite simple using a capable text editor. Then you can just glue it together.)

Also I recently wrote a small [python script](https://github.com/dennmuel/custom-packs/blob/master/deck.py) to create and "edit" decks (no card editing yet). So once you have a JSON file you can use it to sort cards, update the count and add new cards (that are checked for duplicates). Or if you have a text file feel free to add a "create from file" PR (or any other improvements).

**Comment by jakelauer** [comment]
This is supported now
