### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by bjohnson0604** [jakelauer/allbadcards#34]
We’re obsessed. Thank you. You are absolutely saving us during quarantine. 

A few additional ideas that are all probably already in the works:

- custom card upload (through excel/doc at beginning of every game?)
- ability to play two white cards in a turn and risk losing a black card point if one of your white cards isn’t chosen 
- option to have black card winner as next card czar instead of order of players joined

Love this so much.

**Comment by jakelauer** [comment]
<3 Good ideas!

**Comment by jakelauer** [comment]
#97 for the first item you listed

**Comment by jakelauer** [comment]
CardCast is now supported!

**Comment by jakelauer** [comment]
Round winner becoming the czar is now supported :)

**Comment by jakelauer** [comment]
I'm gonna call this closed. The 2nd idea is a very specific house rule. If more requests are made, I will consider.
