### ISSUE TITLE
Dark mode deletes chat

### ISSUE THREAD

**Issue by mdrake1** [jakelauer/allbadcards#343]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
allbad.cards/game/heathen-beaver-7129/play
2. Describe the problem you experienced
If you switch in/out of dark mode, it deletes everything in the chat function
3. Did you see any errors?
The game was fine, but it was kinda sad to miss the chats from before. 
4. Screenshots - If applicable, add screenshots to help explain your problem.
It just reset to the default empty screen on chat.
5. Additional information
Please provide any additional helpful information, like:
- Browser Google Chrome
- Device type PC

**Comment by jakelauer** [comment]
The chat history is not kept in a way that makes it easy to persist. This is by design, for performance reasons, though I agree it would be nice to have.
