### ISSUE TITLE
All Bad Cards - Indian Version

### ISSUE THREAD

**Issue by bechiranjeet** [jakelauer/allbadcards#347]
My idea is...
to have Indian version of this starting with language Hindi and then including Bengali, Oriya, Tamil, and Telugu. This would popularise the game even more into Indian population. Many of the local or desi or hindiglish kind of cards could be introduced.

**Comment by jakelauer** [comment]
Closing in favor of #348

**Comment by bechiranjeet** [comment]
Appreciate it. cheers for the work.
