### ISSUE TITLE
See winning hand history within game

### ISSUE THREAD

**Issue by christiebp** [jakelauer/allbadcards#352]
My idea is...
My friends and I would LOVE to be able to go back and review the winning cards for each hand -- even just from within the same game. I have no idea how easy or hard that would be to do... I was thinking maybe it could be part of the scoreboard (like if you click the player's name it shows their winning matches? 

Anyway LOVE the game: it has honestly made this quarantine more bearable. Thank you.

**Comment by dennmuel** [comment]
Thanks for the idea, @christiebp! I'm not quite sure, but it sounds like #78 to me and I fear we'll have to close this one for the same reasons. We'll have to wait for @jakelauer's view on this.

**Comment by jakelauer** [comment]
Agree. This is an oft-requested feature, but I don't see a future for it, for these reasons:

- It would require a deep refactor of the round logic
- It would inflate the size of the package sent to the clients each round, which would make a huge dent in the data cost for the site
