### ISSUE TITLE
getting error "Could not find plugin "proposal-class-properties"." when i run command yarn start

### ISSUE THREAD

**Issue by nikultaka** [jakelauer/allbadcards#354]
when i run the command yarn start, i am getting error :
**Could not find plugin "proposal-class-properties". Ensure there is an entry in ./available-plugins.js for it**
to resolve this issue, i have added  this code in package.json

> "resolutions": {
>     "@babel/preset-env": "7.5.5"
>   }

and then i run this command, npx npm-force-resolutions,  but still not working 
can you please help me which steps should i take now ?

**Comment by jakelauer** [comment]
Which version of Yarn do you have installed? Did you run the install steps?

**Comment by nikultaka** [comment]
I am using yarn version : 1.22.4

**Comment by nikultaka** [comment]
yes i installed all that steps which is mention in the doc

**Comment by nikultaka** [comment]
thanks, it is working now
