### ISSUE TITLE
Spelling error in one of your cards

### ISSUE THREAD

**Issue by brittniecole** [jakelauer/allbadcards#355]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

https://allbad.cards/game/arrested-clam-6865/play
(we continued playing so if this is not correct i apologize.

2. Describe the problem you experienced

There was a spelling error in one of your cards. 

3. Did you see any errors?
![allcards](https://user-images.githubusercontent.com/57958341/84561454-8b892f80-ad1a-11ea-871f-5575d6629f08.png)

It says "i" instead of "it"

4. Screenshots - If applicable, add screenshots to help explain your problem.

See above

5. Additional information
Please provide any additional helpful information, like:
- Browser - Chrome
- Device type - Windows

Hello, I noticed an error in one of your cards. (See information above). I am a QA engineer and seeing this made me think about your QA, and wondering if it is the best. Not all of your cards have errors, but as they tell me in my role, errors will not make your customers visit you again. I love this website so it is not a dig, I am just hyperfocused on things that don't matter. If you would like hire me to help you QA, I would be more than happy to. I wish you the best.

Thank you,
Brittnie

**Comment by dennmuel** [comment]
Thanks for the hint, @brittniecole! Assuming the author of the card made only one typo, I'd personally change it to "I was not surprised" instead of "It was no surprise", if you're okay with it. :)
