### ISSUE TITLE
Runbook and documentation

### ISSUE THREAD

**Issue by archer007** [jakelauer/allbadcards#359]
My idea is...
Can you create a dockerized version of this app or a runbook showing how to get it running with a fresh Ubuntu install? I immediately ran into problems figuring out which version of yarn to use and how to configure it. Probably easy when you use it every day but having a path to a successful build would help immensely for people who don't know the stack that this app uses.

**Comment by dennmuel** [comment]
Hi @archer007!
There is already a [dockerfile available here](https://github.com/jakelauer/allbadcards/blob/master/Dockerfile). Also you may want to look at #311 for some more details about yarn (haven't checked if the version is mentioned there, just remembered that issue exists).

**Comment by jakelauer** [comment]
You shouldn't run into any problems with Yarn, as there is a yarn lock file. You just have to install the version I linked to and run the install steps as described.
