### ISSUE TITLE
Show progress bar when card czar is going through white card submissions

### ISSUE THREAD

**Issue by insectatorious** [jakelauer/allbadcards#36]
We played with 12 people and it was easy to lose track of how many submissions were left (IRL we would see the remaining white cards). It could be as simple as a progress bar spanning the width of the view. Or a counter that updates in the corner (1/12...2/12 etc).

**Comment by AntonioGargaro** [comment]
+1

**Comment by jakelauer** [comment]
Done! Now shows a counter
