### ISSUE TITLE
All Bad Cards is glitching like crazy!  

### ISSUE THREAD

**Issue by denster24** [jakelauer/allbadcards#361]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?  https://allbad.cards/

2. Describe the problem you experienced.  I play this card game with my friends every week and this week there were a ton of problems.  Games were glitching and people kept trying to add themselves even though the game wasn't public.

3. Did you see any errors?  Yes it would say to refresh and then I would and it would kick me out of the game.

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
All of us were having the same problems.

**Comment by jakelauer** [comment]
Please link to the game in question

**Comment by jakelauer** [comment]
Did you leave the tab or window for long periods of time? This sounds like the autokick behavior which is only for public games. Are you sure the game wasn't public?

**Comment by jakelauer** [comment]
Closing due to lack of response, but can open if more info is given.

**Comment by denster24** [comment]
https://allbad.cards/game/entangled-jay-8407

https://allbad.cards/game/confidential-sloth-1402

These are the links to the 2 games we played on Saturday.  All of the players had the same issues.  We've never had issues with the game before, but I had about 50 different people try and add the game even though it wasn't public and every time I would deny access, the game would glitch and skip people's turns.  None of us had multiple tabs up.  Some were playing on phones, some one desktops, some were PC and some were MACs.

We love your site and multiple people in our group have bought you several coffees 🙂 This is the first time we had problems.

On another note, it would be awesome if you could save the settings when I select the decks we are using.  It takes me a while to go through the decks each week to figure out which ones to use.  Also it is a little bit of guess work on what is in each deck.

Love the game!

Dennis

________________________________

**Comment by jakelauer** [comment]
Thanks for the details! Drilling into it further, it appears people were reaching your games from the `/games` page, which is indicative of three possibilities:

1) You made your game public accidentally at some point, and people found it on the games page and joined it. Or,
2) There is a bug in the UI that cause the game to be marked public, or
3) There's a bug in the server that caused a private game to be shown on the games page.

Option 1 sounds the most plausible to me, given that I haven't really seen this happen at all to anyone else. However, it's possible that 2 or 3 are happening. It'll be quite difficult to diagnose how that could happen without more data though :(

**Comment by denster24** [comment]
Cool no worries!  We figured it was just a one time glitch.

Here are a couple of things that I'm not sure if you can help with:

  1.   I have an account with the allbadcards site...is there a way we could save our settings so that we can use the same packs from previous games?
  2.   Is there a way we can know what some of the packs are?  I see the titles, but I don't know the content and I can't figure it out from the titles (i.e. Carbs of the Huge Manatee, Cats Abiding Horribly, etc.)

Other than that, your game has been a wonderful way to pass the time during quarantine.  We've had some GREAT times with it.  Thanks!

Dennis

________________________________
