### ISSUE TITLE
Player removed from game

### ISSUE THREAD

**Issue by AmyJ20** [jakelauer/allbadcards#367]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/didactic-rattlesnake-8677
2. Describe the problem you experienced
One player was unable to continue game - others weren't able to continue as player marked as idle.
3. Did you see any errors?
Error code mentioning connection
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser Chrome
- Device type android mobile

**Comment by jakelauer** [comment]
Anyone receiving this error can refresh and rejoin.

**Comment by AmyJ20** [comment]
Hi Jake,From what I remember we did try this, but the person who was frozen out could not rejoin - the only way they could join was to create a new player, but that meant the game was still waiting for their original profile to take their turn, so no one could go any further.On 17 Jul 2020 07:35, Jake Lauer <notifications@github.com> wrote:
Anyone receiving this error can refresh and rejoin.

**Comment by jakelauer** [comment]
This would only happen if the person joined using a different browser, or if they were using something like an in-app browser (e.g. opening it up from Facebook Messenger or similar). Also, if this does happen, the game owner can always kick the idle player.
