### ISSUE TITLE
Batch edit custom packs and/or delete packs.

### ISSUE THREAD

**Issue by hcaz282** [jakelauer/allbadcards#370]
My idea is...
I love the feature to batch add cards, but it would be great if there was a way to batch edit cards as well OR be able to delete a pack. i accidentally uploaded a list of cards I forgot to check for grammar.

THANKS!

**Comment by dennmuel** [comment]
Hi @hcaz282, thanks for your suggestion!
I can't comment on the batch edit suggestion itself, but what you could do to fix the specific problem with your pack would be to export the whole pack as a JSON file, edit this (with an ordinary text editor) and import the edited JSON file overwriting the old version of the pack using the "replace pack" option.

![grafik](https://user-images.githubusercontent.com/21078769/85257227-c6e7d480-b465-11ea-81fd-91f81ba5fe2f.png)

Hope this helps for now. :)

**Comment by jakelauer** [comment]
^ this is why that feature exists! :)
