### ISSUE TITLE
Ability to see who chose what cards at the end of each round

### ISSUE THREAD

**Issue by BenKennish** [jakelauer/allbadcards#371]
My idea is...

My friends and I would really love it if there was an option that allowed you to see who chose what white cards at the end of the round once the winner has been chosen.  Yes we can talk about it but it'd be a lot easier if we could just see a name next to each white card and then we can laugh and talk about it immediately.

Keep up the good work and, if you implement this, let me know and I'll happily make a donation.

Thanks! ❤️

**Comment by jakelauer** [comment]
I understand that this would be easier to see than to talk about, but I think it's actually a fun thing to talk about it, and it could be seen as a bit of a spoiler if it always said who played what.
