### ISSUE TITLE
lost connection

### ISSUE THREAD

**Issue by Tensoup** [jakelauer/allbadcards#373]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/civic-fireant-1300/play
2. Describe the problem you experienced
player was not able to pick the winner, then the winner was only displayed on one persons screen, the rest of us got lost connection, retry button didnt work.
3. Did you see any errors?
lost connection
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser: Chrome
- Device type: desktop computer

**Comment by jakelauer** [comment]
Maybe everyone was idling? I haven't seen other reports like this. Closing unless other people find similar issues.
