### ISSUE TITLE
Rando Cardrissian

### ISSUE THREAD

**Issue by dirtside** [jakelauer/allbadcards#374]
My idea is...
Add an option when setting up a game to have one (or more?) AI players named Rando Cardrissian, who will play a random card each time. This is helpful when you have a small number of players and want extra options to pad out the choices each round.

**Comment by jakelauer** [comment]
This already exists. You can add AI players to games during game creation.

**Comment by dirtside** [comment]
Thanks, somehow I missed that (several times) during game setup. /facepalm
