### ISSUE TITLE
Custom pack dropping (random?) cards on save

### ISSUE THREAD

**Issue by kristenmaxwell** [jakelauer/allbadcards#377]
1. What URL was your game at?
https://allbad.cards/pack/detail/s07_sQcxE
Although it happens on multiple packs, even creating one from scratch.

2. Describe the problem you experienced
Every time I try to save the deck, it truncates the number of white cards. Initially it shows all 1000 cards I imported through the multi-card window. When I save, it culls the count down to 994, seemingly at random?

3. Did you see any errors?
More than once, on initial save i have gotten an error of "pack not found" or something similar.

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
Win10, Firefox 77.0.1

**Comment by jakelauer** [comment]
This is almost certainly due to new behavior that removes duplicates. People reported duplicate cards showing up, so now saving the pack will remove dupes.

**Comment by kristenmaxwell** [comment]
interesting. that's actually a great feature. I'll check my source list to see if that's it. Thanks!
