### ISSUE TITLE
Set a timeout when someone don't pick the card for a long time

### ISSUE THREAD

**Issue by victorfadias** [jakelauer/allbadcards#381]
My idea is...

**Comment by sadokx** [comment]
This is incredibly annoying. If they also lose connection then the game is stuck forever.

**Comment by dennmuel** [comment]
Hi :) Not sure if I understand you correctly, but doesn't this gameplay setting work for you?
![grafik](https://user-images.githubusercontent.com/21078769/87277343-638c1800-c4e2-11ea-9691-2040a2d9fd56.png)

**Comment by jakelauer** [comment]
^ this should work

**Comment by jakelauer** [comment]
> This is incredibly annoying. If they also lose connection then the game is stuck forever.

The owner can kick players who go idle.
