### ISSUE TITLE
All Bad Cards bug

### ISSUE THREAD

**Issue by Marshmallow770** [jakelauer/allbadcards#382]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/
2. Describe the problem you experienced
when anything happened, it wouldn't show up until I refreshed. When I clicked a button nothing would happen until I refreshed. It wasn't just me, my friend's experienced it too, even when I wasn't hosting the game. 
3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
Sorry about that, it's fixed now!
