### ISSUE TITLE
Ghost Hand

### ISSUE THREAD

**Issue by lwright88** [jakelauer/allbadcards#39]
My idea is...
Hi!  My idea is to add a ghost hand, where random cards are selected from a "ghost person".  We play this with the in-person game and the results are hilarious.

**Comment by jakelauer** [comment]
This is possible now! You can add random players before the game starts and they will play as ghost players.

**Comment by lwright88** [comment]
They are ghost hands!? Awesome!

**Comment by lwright88** [comment]
Thanks for getting back to me so quickly.  I'm supporting you on Patreon!

**Comment by jakelauer** [comment]
<3 Thank you so much!
