### ISSUE TITLE
LOTS OF ERRORS

### ISSUE THREAD

**Issue by hcaz282** [jakelauer/allbadcards#390]
playing at allbad.cards
error messages
"you've submitted wrong number of cards, expected 1 but received 2"

there were 2 times using 5 different links where there were different black cards showing on different screens

freezes the game. we had to use 5 links to play tonight.
PLEASE fix, you are the one one left, all other CAH games are gone

thank you so much!
Zach

***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
I can't fix this without knowing what cards you saw the errors on. Haven't received any other reports of this!

**Comment by hcaz282** [comment]
we are using only our own card packs!!

pack code  rzafBN9bc

----
Cantor Zachary M. Mondrow
(646) 512-1844
www.zachmondrow.com

Wine and Whiskey Tastings In *YOUR* home...
www.decanterzach.com
Stave & Thief Society- Certified Executive Bourbon Steward
Wine & Spirits Education Trust (WSET)- Certified Level 3 Wines,  Level 2 in
Wine & Spirits

**Comment by jakelauer** [comment]
Have you edited them recently, like within the last couple weeks? There was a bug before that was fixed that resulted in this error. If you haven't, try editing it again. 

Otherwise, I'll check it out.

**Comment by hcaz282** [comment]
That card pack gets changed weekly. We are constantly adding new cards,
both white and black


------
Cantor Zachary M. Mondrow
(646) 512-1844
www.zachmondrow.com

-Wine/Liquor Tastings in YOUR home
www.decanterzach.com

Stave & Thief Society- Certified Executive Bourbon Steward

Wine & Spirits Education Trust (WSET)- Certified Level 3 Wine, Level 2
Spirits

**Comment by hcaz282** [comment]
Our card link
https://allbad.cards/game/alienate-panther-2171


------
Cantor Zachary M. Mondrow
(646) 512-1844
www.zachmondrow.com

-Wine/Liquor Tastings in YOUR home
www.decanterzach.com

Stave & Thief Society- Certified Executive Bourbon Steward

Wine & Spirits Education Trust (WSET)- Certified Level 3 Wine, Level 2
Spirits

**Comment by jakelauer** [comment]
Did you have custom input enabled for these games?

**Comment by hcaz282** [comment]
Yes. Our favorite feature


------
Cantor Zachary M. Mondrow
(646) 512-1844
www.zachmondrow.com

-Wine/Liquor Tastings in YOUR home
www.decanterzach.com

Stave & Thief Society- Certified Executive Bourbon Steward

Wine & Spirits Education Trust (WSET)- Certified Level 3 Wine, Level 2
Spirits

**Comment by jakelauer** [comment]
So I am not seeing any errors, myself. However, I added better logging to try to detect this when it happens. I see errors in the logs, but they don't show enough information for me to solve the problem.

**Comment by hcaz282** [comment]
Ok, next time we play I'll take screenshots


------
Cantor Zachary M. Mondrow
(646) 512-1844
www.zachmondrow.com

-Wine/Liquor Tastings in YOUR home
www.decanterzach.com

Stave & Thief Society- Certified Executive Bourbon Steward

Wine & Spirits Education Trust (WSET)- Certified Level 3 Wine, Level 2
Spirits

**Comment by jakelauer** [comment]
Closing until further info appears!

**Comment by hcaz282** [comment]
Hi,
things were much better this week. i went into our JSON for the card pack
and found a random " in a card that was probably throwing errors.

however, we got this message tonight and it completely stalled the game. it
would not advance to the next round.

also, during the reveal, people were not all seeing the same cards,
typically there were 2 versions that were seen by half the group.
[image: Screenshot 2020-07-19 22.52.25.png]

THANKS!

oh, please send me your venmo


----
Cantor Zachary M. Mondrow
(646) 512-1844
www.zachmondrow.com

Wine and Whiskey Tastings In *YOUR* home...
www.decanterzach.com
Stave & Thief Society- Certified Executive Bourbon Steward
Wine & Spirits Education Trust (WSET)- Certified Level 3 Wines,  Level 2 in
Wine & Spirits

**Comment by jakelauer** [comment]
I don't think your image attached successfully, maybe upload it on the GitHub page?

**Comment by hcaz282** [comment]
Sorry, it ended up in the body of the email.


------
Cantor Zachary M. Mondrow
(646) 512-1844
www.zachmondrow.com

-Wine/Liquor Tastings in YOUR home
www.decanterzach.com

Stave & Thief Society- Certified Executive Bourbon Steward

Wine & Spirits Education Trust (WSET)- Certified Level 3 Wine, Level 2
Spirits

**Comment by hcaz282** [comment]
hey did you ever get the updated screenshot? i'm reattaching.
everyone got the error on their screens. i was the last to get it. i tried
kicking everyone out of the game hoping it would reset, but once i did
thats when i got the error message.

btw i figured i bother you enough so i became a patron. would you prefer i
use the patron portal? or is email easier?

thanks
Zach

----
Cantor Zachary M. Mondrow
(646) 512-1844
www.zachmondrow.com

Wine and Whiskey Tastings In *YOUR* home...
www.decanterzach.com
Stave & Thief Society- Certified Executive Bourbon Steward
Wine & Spirits Education Trust (WSET)- Certified Level 3 Wines,  Level 2 in
Wine & Spirits

**Comment by hcaz282** [comment]
oops...forgot to attach

hey did you ever get the updated screenshot? i'm reattaching.
everyone got the error on their screens. i was the last to get it. i tried
kicking everyone out of the game hoping it would reset, but once i did
thats when i got the error message.

btw i figured i bother you enough so i became a patron. would you prefer i
use the patron portal? or is email easier?

thanks
Zach

----
Cantor Zachary M. Mondrow
(646) 512-1844
www.zachmondrow.com

Wine and Whiskey Tastings In *YOUR* home...
www.decanterzach.com
Stave & Thief Society- Certified Executive Bourbon Steward
Wine & Spirits Education Trust (WSET)- Certified Level 3 Wines,  Level 2 in
Wine & Spirits
