### ISSUE TITLE
Trying to remove a card from my deck causes random other cards to be removed.

### ISSUE THREAD

**Issue by AlexReynard** [jakelauer/allbadcards#393]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at? https://allbad.cards/game/duplicate-fireant-10000

2. Describe the problem you experienced

So I spent a long time building up my deck today. We started play, a friend noticed a spelling error, so I went to correct it. I put a word in the card into the filter; there it is. But I can't change the card. Instead, it creates a duplicate card with the original, incorrect spelling. And I can't remove the duplicate. I click on 'remove' and it stays there. I keep clicking out of frustration, and notice that the number of cards in the deck is going down! TRYING TO REMOVE THIS CARD INSTEAD REMOVES RANDOM CARDS IN THE DECK!!! WHAT THE HELL!?

We thought maybe the problem was caused by the deck currently being in use, so we tried to end the game because we'd only done one round. None of us could figure out how to end the game. We all left, but then the one remaining player _couldn't_ leave. I couldn't find any 'end game' button. How does this make any sense?

3. Did you see any errors? no

4. Screenshots - If applicable, add screenshots to help explain your problem.

Can't. I tried logging out, to see if that would end the game, and now I can't log in because Patreon decided to go down for maintenance right now. (Why, of all things, tying your login to Patreon!?)

5. Additional information
Please provide any additional helpful information, like:
- Browser Firefox 78.0.2
- Device type Desktop computer, Windows 7 professional

**Comment by AlexReynard** [comment]
Oh, and the game was showing different revealed cards to different players.

As in, three of us saw cards A B C D E

Two of us saw cards A F G H E

**Comment by AlexReynard** [comment]
Oh, and the game was showing different revealed cards to different players.

As in, three of us saw cards A B C D E

Two of us saw cards A F G H E

EDIT: This keeps happening. In fact, it seems the Card Queen is sometimes not seeing the card that the player actually entered. This is not good.

**Comment by AlexReynard** [comment]
The two of us seeing different cards are in the same house, on the same network. The others are in Canada and Connecticut, respectively.

**Comment by jakelauer** [comment]
You're correct, I see the error about removing cards while filtering as well. I will fix that up.

Games can't be ended except by somebody winning. There's no real point to ending a game, since games are generally private and you can just leave games when you're finished playing, if there's no winner. If you really want a winner, you can change the setting for Rounds to Win to a number lower than the winningest player's score.

Patreon makes the most sense for OAuth, because I have Patreon supports and would like to give them benefits. 

Revealed cards are all based on the same data, so if players are seeing different cards, their browser probably missed an update. 

To be honest, the fact that you have experienced so many issues at the same time makes me think the Occam's Razor here is that there's something up with either your connection, or card pack, or something. These are not issues I see reports about. Were you editing a deck in the middle of playing? Each player's browser downloads the deck when it needs it, and if you've edited a deck mid-game, different versions of the same deck may be present on each browser. I can't prevent you from editing a deck while you play, but it's probably gonna cause some problems.

**Comment by AlexReynard** [comment]
Damn, dude! I appreciate the quick reply! : D


>You're correct, I see the error about removing cards while filtering as well. I will fix that up.


Excellent. My deck is enormous (95 pages) as I've just been copying over screenshots of old games with the Cardcast decks. So trying to find an individual card in there manually is next-to-impossible.


>If you really want a winner, you can change the setting for Rounds to Win to a number lower than the winningest player's score.


That makes sense! We'll remember that.


>Patreon makes the most sense for OAuth, because I have Patreon supports and would like to give them benefits.


Allright. It was just annoying in that, I had to wait until their site returned before I could check my deck again.


>To be honest, the fact that you have experienced so many issues at the same time makes me think the Occam's Razor here is that there's something up with either your connection, or card pack, or something. These are not issues I see reports about. Were you editing a deck in the middle of playing? Each player's browser downloads the deck when it needs it, and if you've edited a deck mid-game, different versions of the same deck may be present on each browser.


That would definitely explain it. I didn't realize different people would be downloading the deck at different times, so yeah, when several cards got removed accidentally (I'm very glad I was able to refresh the page without saving and get them back!) maybe they were either missing from some decks, or when I returned them, it added duplicates to other decks.


>I can't prevent you from editing a deck while you play, but it's probably gonna cause some problems.


If you can't lock a deck, maybe at least make a note of it on the site somewhere? 'Don't do this or your game will get weird'.


BTW, we did end up getting everything working with someone else hosting and hunting down my deck. Had a damn good game.





________________________________

**Comment by jakelauer** [comment]
Yeah, it'd be smart to put a note somewhere, although with the public decks, anyone could be playing with any deck at any time. The BEST option would be to create a versioning system such that when you start playing, you are using the version of the deck that existed at the time of the game. Which sounds like a lot of work :P Maybe there's another way.

**Comment by AlexReynard** [comment]
Good luck on whatever you decide!

________________________________

**Comment by jakelauer** [comment]
Fixed!

**Comment by AlexReynard** [comment]
Congrats!! I can confirm that I can now remove cards without any problem.

________________________________
