### ISSUE TITLE
Error Encountered when trying to save my deck.

### ISSUE THREAD

**Issue by AlexReynard** [jakelauer/allbadcards#398]
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/fledgling-gorilla-8327

2. Describe the problem you experienced
Cannot save my deck

3. Did you see any errors?
"Error Encountered
JSON.parse: unexpected character at line 1 column 1 of the JSON data"

4. Screenshots - If applicable, add screenshots to help explain your problem.
https://i.imgur.com/dHOTis5.png

5. Additional information
Please provide any additional helpful information, like:
- Browser Firefox, latest version
- Device type Desktop computer, Windows 7 Professional

**Comment by AlexReynard** [comment]
It just occurred to me, the actual json header might be helpful

{
  "ownerId": "41551",
  "packId": "OnxwPPcqA",
  "packName": "Fox Droppings",
  "whiteCards": [
    "Muhammad Ali",
    "dirty little mousie feet",
    "the oh-so-quiet public library",
    "traditional 4th Of July anus firecrackers",

**Comment by jakelauer** [comment]
My guess is that your file has some kind of strange format. Could you upload the JSON file here?

**Comment by AlexReynard** [comment]
It's the same file that's already on your site. I got the JSON data by exporting it, not importing it.

It was also giving me this error alongside several ones about copyrighted content. Which I'm guessing, I copied over some original CAH cards. Fine. I've been cutting those as errors point them out. But I'm still getting the JSON error. Even though, weirdly, it DOES seem to be saving. I can refresh the page and my changes are still there.

________________________________

**Comment by jakelauer** [comment]
That pack ID gives me a different pack. Is it perhaps a different ID?

**Comment by AlexReynard** [comment]
I remade the entire deck from scratch to see if that would fix things. Nope. I'm still getting the 'encountered an unexpected character [pauses, then goes to check] Actually, no! The new deck is saving correctly now! I have no bloody idea how that happened!! :D

All's well that ends well, I guess!

________________________________

**Comment by jakelauer** [comment]
Weird! Closing :P
