### ISSUE TITLE
Menu bar for card game selection overflows 

### ISSUE THREAD

**Issue by phelantomas** [jakelauer/allbadcards#4]
![CB7365E9-CF39-4C25-8DA9-CA133F44C626](https://user-images.githubusercontent.com/31985716/79102892-f4304c00-7d6b-11ea-87a0-a77370d082ba.png)

Occurs on iPhone XR

**Comment by jakelauer** [comment]
Good find, thanks!

**Comment by jakelauer** [comment]
Fixed!
