### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by henryjarend** [jakelauer/allbadcards#40]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/brave-wasp-13

2. Describe the problem you experienced
Unexpected token randomly during gameplay

3. Did you see any errors?
Yes
![Screenshot_20200417-214249_Firefox](https://user-images.githubusercontent.com/2661636/79625101-9fd2f680-80f4-11ea-8c05-5f34df031baf.jpg)

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser Firefox mobile, chrome
- Device type, laptops and mobile

**Comment by jakelauer** [comment]
I just pushed out an update to hopefully address this. Traffic is SUPER high right now - 4x my highest before today. Sorry about the inconvenience!
