### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by kmhiggins** [jakelauer/allbadcards#41]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/red-ladybug-36
2. Describe the problem you experienced
T token error, no cards available for one player
3. Did you see any errors?
unexpected token T
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
-Chrome
-Custom build computer

**Comment by jakelauer** [comment]
I just pushed out an update to hopefully address this. Traffic is SUPER high right now - 4x my highest before today. Sorry about the inconvenience!
