### ISSUE TITLE
Unable to click the "my cards suck" button after starting new game

### ISSUE THREAD

**Issue by Lukecorrigall-GBI** [jakelauer/allbadcards#42]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/nasty-rat-66

2. Describe the problem you experienced
After finishing the first game and choosing to do another gamne, none of the players could click the "My Cards Suck" button -- it was greyed out saying that you could only use it every 5 rounds

3. Did you see any errors?
Yes, we were getting token errors, but seemed unrelated

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

Multiple browsers and devices had the same problem

**Comment by AndreasGassmann** [comment]
We just experienced the same issue. One guy said after like 10 rounds it suddenly worked again, but for the others including me it didn't. URL was https://allbad.cards/game/lovely-robin-27

**Comment by jakelauer** [comment]
Should be fixed!

**Comment by jakelauer** [comment]
Details in #16
