### ISSUE TITLE
Allbadcards

### ISSUE THREAD

**Issue by ttaylor72** [jakelauer/allbadcards#43]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/helpless-newt-93
2. Describe the problem you experienced
A message kept popping up for multiple players
3. Did you see any errors?
Yes see screenshot
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
-  #Browser
![Screenshot_20200417-221003](https://user-images.githubusercontent.com/63889557/79625731-f3474380-80f8-11ea-9d24-499133f6311c.png)

- Device type

**Comment by jakelauer** [comment]
This should be fixed. I spent many hours this weekend to make this much better.
