### ISSUE TITLE
Cards Against Humanity unexpected tolken, failing game.

### ISSUE THREAD

**Issue by rmerritt0909** [jakelauer/allbadcards#45]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by rmerritt0909** [comment]
Unexptected tolken continually popped up, at some points crashed the game. A lot of cards were reused.

**Comment by jakelauer** [comment]
I just pushed out an update to hopefully address this. Traffic is SUPER high right now - 4x my highest before today. Sorry about the inconvenience!

**Comment by rmerritt0909** [comment]
Thank you! Love the app
