### ISSUE TITLE
The game won’t start

### ISSUE THREAD

**Issue by kookiiu** [jakelauer/allbadcards#46]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/tasty-bat-50
2. Describe the problem you experienced
The game would not start and it would not let us pick a deck
3. Did you see any errors?
“NaN”
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
This should be fixed. I spent many hours this weekend to make this much better.
