### ISSUE TITLE
Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by nathanscotphillips** [jakelauer/allbadcards#53]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at? https://allbad.cards/game/U5NRGngFc

2. Describe the problem you experienced **The error "Unexpected token T in JSON at position 0" kept popping up on at least 4 peoples phones while playing. I tapping somewhere else on the screen would make it go away , it kept coming back. I was able to play the game while it was happening but it did get pretty annoying.**

3. Did you see any errors? **Yes  "Unexpected token T in JSON at position 0"**

4. Screenshots - If applicable, add screenshots to help explain your problem.
![Screenshot_20200417-215606](https://user-images.githubusercontent.com/63924441/79645689-bb361400-817d-11ea-9988-d3feb5004d77.png)

5. Additional information
Please provide any additional helpful information, like:
- Browser **Chrome Version 80.0.3987.162**
- Device type **Google Pixel 3a (Running Android 10)**

**The screenshot was taken on April 17 2020 at 9:56p Eastern time**

**A few hiccups while playing aside, this is awesome especially with the whole global pandemic thing. Thanks guys. Great job!**

**Comment by khloroshue** [comment]
Hey there, didn't want to open a separate issue for this - but I was experiencing the same issue this evening - game URL: https://allbad.cards/game/itchy-frog-0. All participants were using Windows 10 PCs with either Google Chrome or Firefox browsers.

**Comment by jakelauer** [comment]
Can you tell me if this happened when you tried a specific action? Or were you just sitting there and it happened.

**Comment by nathanscotphillips** [comment]
I was trying to select a card to play (scrolling through them) when I took
the screen shot. It may have happened at other times too. I don't remember
exactly.

**Comment by wumb0** [comment]
seems to start happening when the server gets busy, if that helps at all. ill try to keep the debugging console up when it happens to get more info...

**Comment by jakelauer** [comment]
I'm almost certain that it's related to lots of traffic. Before I can reproduce it myself, it would be extremely useful if anyone who knows how could report what's showing up in the problematic network requests either via the Chrome DevTools network tab or Fiddler

**Comment by wumb0** [comment]
Its in a third party module (sentry). maybe a request times out inside sentry and the error isn't handled right. im not a javascript guy so I'm not sure. ill check the network tab for errors please hold.

**Comment by jakelauer** [comment]
Oh! That's actually great news. Maybe much easier to fix. I can't get to it until about 7pm PST but I'll try to fix them

**Comment by wumb0** [comment]
you're a champion. thanks so much for hosting this. I'm going to host my own version for next week i think :)

**Comment by jakelauer** [comment]
Hopefully this is better now. I made some improvements this evening to try to get it fixed

**Comment by jakelauer** [comment]
@wumb0 please note the license if you want to host a version - I would ask for you to ask my permission with details on your plan :) appreciate your activity in these issues!

**Comment by wumb0** [comment]
what's the best way to contact you about that?

**Comment by jakelauer** [comment]
@wumb0 email allbadcards (at) gmail.com

**Comment by jakelauer** [comment]
This should be fixed. I spent many hours this weekend to make this much better.
