### ISSUE TITLE
iPhone user saw skipped card

### ISSUE THREAD

**Issue by nvictoros** [jakelauer/allbadcards#55]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/empty-husky-46

2. Describe the problem you experienced
I was card czar. I skipped one card with a blank in it. One user on mobile saw the card that I skipped instead of the new card when playing.

3. Did you see any errors?
No, but I saved the logs in the dev console as a file if you want to see it (don't know how to attach a file in github)

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type
User who had the problem has an iPhone

**Comment by jakelauer** [comment]
This should be a very rare problem and could be solved by refreshing. I don't think it's fixable unfortunately. The root of the issue is that the server sent an update to the user with the new black card, but the user's device did not receive the data, so it's stuck on the previous black card.
