### ISSUE TITLE
Cardcast integration

### ISSUE THREAD

**Issue by aatifsyed** [jakelauer/allbadcards#57]
My idea is...
https://www.cardcastgame.com/ allows creation of custom black and white decks. 

This feature brings parity with Pretend you're xyzzy

**Comment by jakelauer** [comment]
This is planned! I need to figure a way to do it nicely. Does PYZ just make you use command line commands?

**Comment by aatifsyed** [comment]
Fantastic!

It does: `/addcardcast <CODE>` is the current implementation

**Comment by jakelauer** [comment]
Moving to #97 as the canonical issue for this.

**Comment by jakelauer** [comment]
@aatifsyed Just a heads up, we now have a custom pack creator that supports JSON upload. If you haven't grabbed your pack from our exporter, you can do that and then upload!
