### ISSUE TITLE
how-many-wins-to-win-the-game doesn't work

### ISSUE THREAD

**Issue by Tornadonis** [jakelauer/allbadcards#58]
My idea is...
... it'd be great if the selection of how many wins are required to win the game actually worked ;)

**Comment by jakelauer** [comment]
In which game did you experience this? It has worked when I have used it.

**Comment by Tornadonis** [comment]
yeah sorry, it was on cards against humanity on allbad.cards
yesterday as well as today, on the setting page on the beginning I set the limit to 40 but nevertheless the game ended as soon as someone reached 8
great game tho, love it, makes my life wortb living during corona <3

**Comment by jakelauer** [comment]
Interesting, I haven't tested with a super high number. It would be extremely helpful to have a link to a game that broke this way

**Comment by Tornadonis** [comment]
sure thing:
https://allbad.cards/game/gentle-panther-82
https://allbad.cards/game/purple-rat-48

**Comment by jakelauer** [comment]
I think this is fixed now
