### ISSUE TITLE
All Bad Cards not working :(

### ISSUE THREAD

**Issue by pindarella** [jakelauer/allbadcards#59]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/young-wombat-65

2. Describe the problem you experienced
No start button to begin game - greyed out

3. Did you see any errors?
no error msgs

4. Screenshots - If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/63934194/79673407-6f986000-81a7-11ea-8954-ac89d6bc18b3.png)
(not sure if image will attach)

5. Additional information
Please provide any additional helpful information, like:
- Browser - Opera
- Device type - Macbook

**Comment by jakelauer** [comment]
You cannot start a game with fewer than 2 human players. Messaging of this is improved in a newer version!
