### ISSUE TITLE
After selecting spectate, join is no longer possible

### ISSUE THREAD

**Issue by KaiserPodge** [jakelauer/allbadcards#6]

**Comment by jakelauer** [comment]
Good point, that's annoying. In the meantime, you can [clear your site storage](https://www.howtogeek.com/664912/how-to-clear-storage-and-site-data-for-a-single-site-on-google-chrome/) to fix!

**Comment by jakelauer** [comment]
Done!

**Comment by jakelauer** [comment]
You can now leave and rejoin
