### ISSUE TITLE
unexpected json token at position 0

### ISSUE THREAD

**Issue by BrockRutter** [jakelauer/allbadcards#62]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by wumb0** [comment]
jesus christ dude give some more detail. its probably bc the server is overloaded.

**Comment by jakelauer** [comment]
Working hard to solve this. Number one priority! Agreed with @wumb0 that more detail helps but I realize not everyone who uses ABC will be very familiar with bug reporting procedures
