### ISSUE TITLE
glitchy! 

### ISSUE THREAD

**Issue by g-a-t** [jakelauer/allbadcards#63]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/clever-chicken-75

2. Describe the problem you experienced
Multiple players needed to refresh URL very frequently. 

3. Did you see any errors?
"Unexpected token T in JSON position 0."

4. Screenshots - If applicable, add screenshots to help explain your problem.
N/A

5. Additional information
Please provide any additional helpful information, like:
- Browser
Google Chrome

- Device type
MacBook Pro

**Comment by jakelauer** [comment]
This should be fixed. I spent many hours this weekend to make this much better.
