### ISSUE TITLE
Multiple errors while interacting with game

### ISSUE THREAD

**Issue by gsauns** [jakelauer/allbadcards#64]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

**1. What URL was your game at?**
https://allbad.cards/game/afraid-firefox-25

**2. Describe the problem you experienced**
Multiple error dialogs appear at certain clicks. Hard to find a consistent pattern, but it happens every round. Clicking on the page anywhere allows the game to continue normally.

**3. Did you see any errors?**
This error in the console accompanied a blank modal:
```
The service is unavailable. instrument.js:139:35
    se instrument.js:139
    <anonymous> ErrorDataStore.ts:16
```

Modal message: _JSON.parse: unexpected character at line 1 column 1 of the JSON data_
```
SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data" 3.a44ee1fd.chunk.js:1:476733
    se https://allbad.cards/static/js/3.a44ee1fd.chunk.js:1
    <anonymous> https://allbad.cards/static/js/main.66983645.chunk.js:1
```

**4. Screenshots - If applicable, add screenshots to help explain your problem.**
<img width="1909" alt="Screen Shot 2020-04-18 at 8 28 58 PM" src="https://user-images.githubusercontent.com/12153442/79677274-2e0eb180-81b5-11ea-96f3-f20659429a7c.png">

**5. Additional information**
Please provide any additional helpful information, like:
- Browser: Experienced in both Chrome & Firefox
- Device type: Mac

**Comment by jakelauer** [comment]
This should be fixed. I spent many hours this weekend to make this much better.
