### ISSUE TITLE
my cards suck bug

### ISSUE THREAD

**Issue by dooguls** [jakelauer/allbadcards#65]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/fresh-vampirebat-99
2. Describe the problem you experienced
when i pushed 'my cards suck' button the interface wouldn't "submit" my entry and the game stuck waiting for me. but there was nothing i could do, since the 'game' was submitting a card for me.
3. Did you see any errors?
no
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser - chrome
- Device type - windows 10

**Comment by jakelauer** [comment]
I believe this should be fixed by refreshing
