### ISSUE TITLE
SERVER CRASHING!

### ISSUE THREAD

**Issue by GUP1138** [jakelauer/allbadcards#66]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/tall-dragon-8

2. Describe the problem you experienced
'SERVER NOT AVAILABLE"m

3. Did you see any errors?
'JSON" error

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

KEPT HAPPENING ALL THE TIME - FOR WHOLE GROUP PLAYING ON DIFFERENT DEVICES!!!!

**Comment by jakelauer** [comment]
Yep, that sucked. Sorry about that, I'm working hard to solve this
