### ISSUE TITLE
Ability to force start judging (skip a few people)

### ISSUE THREAD

**Issue by 20zinnm** [jakelauer/allbadcards#72]
When someone has to step away from the game, it'd be nice to be able to force them to randomly pick by "force starting judging."

**Comment by jakelauer** [comment]
Would a round timer suffice for the same problem?

**Comment by 20zinnm** [comment]
@jakelauer It probably would. Didn't think of that at 1AM 🤣

**Comment by jakelauer** [comment]
Given that, I'll call this a dupe of #89
