### ISSUE TITLE
"My Card Suck" doesn't seem to work on IPhone

### ISSUE THREAD

**Issue by benji2290** [jakelauer/allbadcards#73]
My idea is...

**Comment by jakelauer** [comment]
What iPhone do you have? Did other players also report this in your party?

**Comment by benji2290** [comment]
Thanks for the response, it appears to have been user error, I'll respond
with more info if we can reproduce it.

Thanks,

Ben

**Comment by jakelauer** [comment]
Closing pending further evidence
