### ISSUE TITLE
White card text does not show up

### ISSUE THREAD

**Issue by kylemiller** [jakelauer/allbadcards#74]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/perfect-mouse-56

2. Describe the problem you experienced
The top-left white card shows up as "0".  (I think the card is "Coat Hanger Abortions")

3. Did you see any errors?
No console errors.   No in-game errors.

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser - Chrome
- Device type - Macbook Pro

**Comment by jakelauer** [comment]
I think this is fixed
