### ISSUE TITLE
Error when kicking another player out after kicking yourself out

### ISSUE THREAD

**Issue by bbbco** [jakelauer/allbadcards#83]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://not.allbad.cards/game/rotten-mouse-24
2. Describe the problem you experienced
I kicked myself out, and then tried to kick another player out
3. Did you see any errors?
Yup
4. Screenshots - If applicable, add screenshots to help explain your problem.
![Screenshot_20200420-210054_Firefox](https://user-images.githubusercontent.com/30680/79813713-68f61e00-834a-11ea-9f96-57ed765eae78.png)

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
This is by design, but the error should look nicer ideally.
