### ISSUE TITLE
Wrong cards

### ISSUE THREAD

**Issue by JosJoz** [jakelauer/allbadcards#85]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/weak-rabbit-46
2. Describe the problem you experienced
When picking a winner it picks a random card instead of the one I chose
3. Did you see any errors?
No
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type
I was using Edge on an Asus laptop. All my friend used Chrome

**Comment by jakelauer** [comment]
Fixed, sorry about that
