### ISSUE TITLE
[Feature request] Languages feature

### ISSUE THREAD

**Issue by Aeroozz** [jakelauer/allbadcards#86]
Hi,

Your game is very funny, we are playing with some friends for couple hours and we're impressed :)
The only complain we have, is the fact we're French, and some references are hard for us to understand.

Is it possible to implement a feature to choose the language ? We saw a JSON file with all the text cards, we can try to translate it in french if you want :) 

Thank you so much

**Comment by jakelauer** [comment]
I would love for you to take a stab at it! I haven't built in localization support in the UI yet but I would be more inspired to do so if there were translations!

**Comment by jakelauer** [comment]
Closed like #20
