### ISSUE TITLE
Game doesn't want to start. 

### ISSUE THREAD

**Issue by AmeerDollie** [jakelauer/allbadcards#87]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced
I added AI players but I couldn't start the game
![Screenshot_20200421_203605_com android chrome](https://user-images.githubusercontent.com/62077682/79901199-c2745080-840f-11ea-96ac-2c746fd919d7.jpg)

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
I need better messaging for this, but you cannot start a game unless you have at least one other human player. This is because the AI players can't act as the Card Czar.

**Comment by AmeerDollie** [comment]
Thanks you
