### ISSUE TITLE
New round timer

### ISSUE THREAD

**Issue by watheuer** [jakelauer/allbadcards#89]
When a rookie player is the Card Czar, they don't always realize that they need to manually move on to the next round after they've picked a winner. This has led to a few unnecessary pauses in our games.

I would suggest a new option for an automatic next round start timer. If a player doesn't manually move on, it moves on for them.

Love the project. If you're looking for contributors, I'd be happy to spend some time on this or another issue.

**Comment by jakelauer** [comment]
Added!
