### ISSUE TITLE
"The string did not match the expected pattern" error

### ISSUE THREAD

**Issue by kaspars-gailitis** [jakelauer/allbadcards#90]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://not.allbad.cards/game/tall-fish-70
2. Describe the problem you experienced
Suddenly stopped showing black cards
3. Did you see any errors?
The string did not match the expected pattern.
4. Screenshots - If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/29582253/80024718-2b2efc00-84e8-11ea-819c-4d548b986dbe.png)
5. Additional information
Please provide any additional helpful information, like:
- Browser Safari
- Device type Mac

**Comment by jakelauer** [comment]
This should be fixed now
