### ISSUE TITLE
Glitching 

### ISSUE THREAD

**Issue by silastheodore** [jakelauer/allbadcards#93]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/tiny-snake-64

2. Describe the problem you experienced
other players experienced glitches where it kicked them out and it wouldn't let other people continue with the game. It once kicked out the Czar but wouldn't let us continue because the czar wasn't there to hit continue, we had to start a new game where it happened again.

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
Did you continue to experience this? I'm not seeing server issues and haven't had other reports of players getting kicked from games. It actually shouldn't be possible to get kicked aside from the game owner removing people.

**Comment by jakelauer** [comment]
Think this is likely resolved
