### ISSUE TITLE
Voting instead of Czars

### ISSUE THREAD

**Issue by DeathwatchDoc** [jakelauer/allbadcards#94]
My idea is...
Add an option to have the winning card(s) selected by a voting system among human players. This is one of our favorite house rule variants and lets everyone play every round preventing the dreaded "Why do I always have the best cards on the rounds I have to judge?" suffering.

**Comment by CryoRig** [comment]
Would love that as an option, but please make it so that you can not vote for your own Card
Or everybody is just gonna vote for themself...

**Comment by DeathwatchDoc** [comment]
We always play it with that specified, forgot to put it in the request as it is second nature. Good catch, thanks!

**Comment by jakelauer** [comment]
Dupe of #71
