### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by djjudas21** [jakelauer/allbadcards#95]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

https://allbad.cards/game/weak-dragonfly-42

2. Describe the problem you experienced

Error message after picking cards, when hitting "Play". Can usually retry and it works, but sometimes the results of the round then include blank cards

3. Did you see any errors?
```
Unexpected token < in JSON at position 0
```
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
- Browser: Chrome
- Device: Linux laptop, also seen on iPhone with Safari

**Comment by jakelauer** [comment]
Working on this

**Comment by jakelauer** [comment]
@djjudas21 How's it looking now?

**Comment by djjudas21** [comment]
Haven't seen the error for a few mins - will let you know. Thanks!

**Comment by djjudas21** [comment]
Yeah, it seems fine now. Thanks for fixing! :+1:

**Comment by jakelauer** [comment]
Thank you for reporting it! It looks like it was happening for a while before anyone said anything :P

**Comment by djjudas21** [comment]
Typical users :wink: I'm a devops engineer by trade so no hardship to log an issue :joy:
