### ISSUE TITLE
CardCast integration, and/or the inclusion of more web-based decks

### ISSUE THREAD

**Issue by Monolithyk** [jakelauer/allbadcards#97]
I have take note of the thread you posted on Reddit, and I did see that a fair amount of people have already requested this feature publicly, but I would like to stress why that it is such a good idea to jump on the CardCast custom card bandwagon.

**Some Points:**
Currently, part fo the allure of your competing sites is their ability to import and/or permanently harbor community-made card expansions. Both azala.info and Pretend You're Xyzzy have their own way of doing this, but it is part of the reason those sites have maintained the success they have for so long. However, both of those sites have their issues, and while many players are looking for a solution like All Bad Cards, the addition of CardCast integration or additional decks may be the push they need to stop relying on other sites. 

**My Main Point:**
Having tested your site extensively, I must say that I am a huge fan of the overall simplicity, design, stability, and if you were to add the feature that makes the other sites so successful, I believe All Bad Cards would become the go-to for web-based Cards Against Humanity.

**--Shameless Bonus Plug!--**
In case you're looking for more cards to host on the site itself w/o CardCast, I also have my own custom decks if you're ever in need of more 3rd party, unofficial cards. One such custom deck is a card deck that is featured as a default deck over on azala.info. The details an be found here:

**Deck Specs**
- Title: Monolithyk's Master of Evil (Original Additions)
- Info: It's a deck with a wide variety of subject matter. Cards in this pack are noticeably more savage than the official game - it's been a personal project of mine since 2011, and has been available online since 2015.
- Card List: https://www.cardcastgame.com/browse/deck/YG9MD
- Author(s): Monolithyk
- Expansion Size: Fucking Ginormous
- Subject Matter: Random
- Twitch Stream Safe: Yes

Again, just in case you need them, there they are. You have my permission to use them if you so choose.

**Comment by jakelauer** [comment]
Yes! This is the very next thing on my list. Today I finished sorting out scaling issues (which was the most important - can't have the site breaking every weekend!) But this is absolutely the next item. 

Here's the current plan:

- When you're creating a game, you will have the option to add CardCast packs by title search or by pack code.
- V2: I would like to create a CardCast card browser that allows you to create a game by browsing available card packs and selecting them as a group. This would also allow for bookmarking particular pack "sets". Might include a Patreon feature to save your own sets to your account.
- V3: Include the most popular packs as choices in the default card pack option list, probably along with swapping out some of the weirder/less popular current ones.

**Comment by jakelauer** [comment]
Also your pack is rad.

**Comment by jakelauer** [comment]
BTW - expect to see the first iteration of this by next week. Potentially this weekend.

**Comment by mavrck307** [comment]
Hi Jake, 
Thanks for this wonderful site. 

Please add my deck. 
Here is the Cardcast link
https://www.cardcastgame.com/browse/deck/UHHUB
GSIS PACK
UHHUB
A community deck created by mavrck
Cards against GSIS is the Official GSIS version of this horrible game for horrible students

**Comment by jakelauer** [comment]
CardCast packs are now supported!

**Comment by Monolithyk** [comment]
Wow - you did such an excellent job with this implementation in a relatively small window of time. I'm really looking forward to seeing this site grow to the acclaim that it clearly deserves.

**Comment by aatifsyed** [comment]
Yes, absolutely fantastic work @jakelauer! 
I hope to become as proficient as you

**Comment by jakelauer** [comment]
Appreciate it! 😊❤

**Comment by jakelauer** [comment]
@Monolithyk  Just a heads up, we now have a custom pack creator that supports JSON upload. If you haven't grabbed your pack from our exporter, you can do that and then upload!
