### ISSUE TITLE
Lounge misspelled on a question card. Was spelled Longe.

### ISSUE THREAD

**Issue by texbob** [jakelauer/allbadcards#98]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/pretty-cow-55
2. Describe the problem you experienced
Lounge misspelled on a question card. Was spelled Longe.
3. Did you see any errors?
Lounge misspelled on a question card. Was spelled Longe.
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment]
No longer an issue in the new cards
