### ISSUE TITLE
Problem with link

### ISSUE THREAD

**Issue by stwaberry** [jakelauer/allbadcards#99]
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/great-bulldog-90
2. Describe the problem you experienced
The game froze at a specific place and refreshing wouldn't work.
3. Did you see any errors?
no
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser: chrome
- Device type: hp laptop

**Comment by jakelauer** [comment]
Not much detail here
